#!/bin/sh
set -eu
systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS XDG_SESSION_TYPE
systemctl --user start pipewire.service pipewire-pulse.service wireplumber.service
systemctl --user start pysh.service
