import {test,expect} from '@playwright/test';
const names:any={en:{disconnect:'Disconnect',connect:'Connect',forget:'Forget device',pair:'Pair',power:'Bluetooth radio',scan:'Scan nearby'},ro:{disconnect:'Deconectează',connect:'Conectează',forget:'Uită dispozitivul',pair:'Asociază',power:'Bluetooth',scan:'Scanează'}};
for(const theme of ['ink','night'])for(const action of ['disconnect','connect','forget','pair','power','scan'])test(`Bluetooth ${theme} ${action}: pending locks and inline retry repeats exact operation`,async({page},info)=>{
const lang=info.project.name.endsWith('ro')?'ro':'en';const device:any={address:'00:11:22:33:44:55',name:'Test speaker',paired:action!=='pair',connected:action==='disconnect'};
const state:any={preferences:{language:lang,theme,setupComplete:true,nightEnabled:false,screensaverMinutes:0},network:{},bluetooth:{available:true,powered:true,devices:[device],prompts:[]},audio:{},player:{},weather:{}};
const writes:any[]=[];let release:()=>void=()=>{};const gate=new Promise<void>(r=>release=r);
await page.route('**/api/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname;if(request.method()==='POST'&&path.startsWith('/api/bluetooth/')){writes.push({path,body:request.postDataJSON()});if(writes.length===1){await gate;await route.fulfill({status:503,json:{error:'bluetooth_unavailable'}});return;}if(action==='power')state.bluetooth.powered=false;else if(action==='scan')state.bluetooth.discovering=true;else if(action==='disconnect')device.connected=false;else if(action==='connect')device.connected=true;else if(action==='pair')device.paired=true;else state.bluetooth.devices=[];await route.fulfill({json:{ok:true}});return;}await route.fulfill({json:path==='/api/state'?state:path==='/api/session'?{token:'fixture'}:{ok:true}});});
await page.goto('/');await page.locator('.rail-bottom button').nth(1).tap();const dialog=page.getByRole('dialog',{name:'Bluetooth',exact:true}),button=dialog.getByRole('button',{name:names[lang][action],exact:true});await button.tap();await expect(dialog.getByRole('status')).toBeVisible();await expect(button).toBeDisabled();await button.evaluate((el:HTMLButtonElement)=>el.click());expect(writes).toHaveLength(1);release();
await expect(dialog.getByRole('alert')).toBeVisible();expect(writes).toHaveLength(1);const before={...writes[0],body:{...writes[0].body}};await dialog.getByRole('alert').getByRole('button').tap();await expect.poll(()=>writes.length).toBe(2);expect(writes[1]).toEqual(before);await expect(dialog.getByRole('alert')).toHaveCount(0);await expect(dialog.getByRole('status')).toHaveCount(0);
if(action==='disconnect')await expect(dialog.getByRole('button',{name:names[lang].connect,exact:true})).toBeVisible();if(action==='connect')await expect(dialog.getByRole('button',{name:names[lang].disconnect,exact:true})).toBeVisible();if(action==='forget')await expect(dialog.getByText('Test speaker',{exact:true})).toHaveCount(0);
await page.screenshot({path:info.outputPath(`bt-${theme}-${action}.png`)});
});
for(const theme of ['ink','night'])for(const setup of [false,true])test(`Location ${theme} setup=${setup}: failed save retains results and retry saves same location`,async({page},info)=>{
const lang=info.project.name.endsWith('ro')?'ro':'en',results=[{name:'București · Sector 5',latitude:44.4,longitude:26.07,country:'Romania'},{name:'București · Sector 6',latitude:44.43,longitude:26.02,country:'Romania'}];
const state:any={preferences:{language:lang,theme,setupComplete:true,nightEnabled:false,screensaverMinutes:0,location:{name:'Old place',latitude:1,longitude:2}},network:{},bluetooth:{devices:[],prompts:[]},audio:{},player:{},weather:{}};const writes:any[]=[];state.preferences.setupComplete=!setup;
await page.route('**/api/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname;if(path==='/api/preferences'){writes.push(request.postDataJSON());if(writes.length===1){await route.fulfill({status:500,json:{error:'preferences_unavailable'}});return;}Object.assign(state.preferences,writes[1]);await route.fulfill({json:state.preferences});return;}await route.fulfill({json:path==='/api/session'?{token:'fixture'}:path==='/api/state'?state:path==='/api/geocode'?{results}:{ok:true}});});
await page.goto('/');if(setup){await page.getByRole('button',{name:lang==='ro'?'Continuă':'Continue',exact:true}).tap();await page.getByRole('button',{name:lang==='ro'?'Continuă':'Continue',exact:true}).tap();}else{await page.locator('.main-nav button').nth(3).tap();await page.locator('.settings-tabs button').filter({hasText:lang==='ro'?'Vreme':'Weather'}).tap();}await page.getByRole('button',{name:'Old place',exact:true}).tap();if(setup)await page.locator('.keyboard-card').getByRole('button',{name:'b',exact:true}).tap();await page.locator('.keyboard-card').getByRole('button',{name:lang==='ro'?'Aplică':'Apply',exact:true}).tap();await expect(page.locator('.geo-item')).toHaveCount(2);await page.locator('.geo-item').first().tap();await expect(page.locator(setup?'.setup-card':'.settings-panel').getByRole('alert')).toBeVisible();await expect(page.locator('.geo-item')).toHaveCount(2);expect(state.preferences.location.name).toBe('Old place');expect(writes).toHaveLength(1);
await page.locator(setup?'.setup-card':'.settings-panel').getByRole('alert').getByRole('button').tap();await expect.poll(()=>writes.length).toBe(2);expect(writes[1]).toEqual(writes[0]);await expect(page.locator('.geo-item')).toHaveCount(0);await expect(page.getByRole('button',{name:results[0].name,exact:true})).toBeVisible();await expect(page.locator(setup?'.setup-card':'.settings-panel').getByRole('alert')).toHaveCount(0);
});
test('Bluetooth accepted mutation plus failed state read only retries status, never the mutation',async({page})=>{
const state:any={preferences:{language:'en',theme:'night',setupComplete:true,screensaverMinutes:0},network:{},bluetooth:{available:true,powered:true,devices:[],prompts:[]},audio:{},player:{},weather:{}};let writes=0,failRead=false;
await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/bluetooth/power'){writes++;failRead=true;await route.fulfill({json:{ok:true}});return;}if(path==='/api/state'&&failRead){failRead=false;await route.fulfill({status:503,json:{error:'backend_unavailable'}});return;}await route.fulfill({json:path==='/api/session'?{token:'fixture'}:path==='/api/state'?state:{ok:true}});});await page.goto('/');await page.locator('.rail-bottom button').nth(1).tap();const dialog=page.getByRole('dialog',{name:'Bluetooth',exact:true});await dialog.getByRole('button',{name:'Bluetooth radio',exact:true}).tap();await expect(dialog.getByRole('alert')).toBeVisible();await dialog.getByRole('alert').getByRole('button').tap();await expect(dialog.getByRole('alert')).toHaveCount(0);expect(writes).toBe(1);
});

for(const theme of ['ink','night'])test(`Geocode ${theme}: explicit retry preserves and repeats the query`,async({page},info)=>{
const lang=info.project.name.endsWith('ro')?'ro':'en';const state:any={preferences:{language:lang,theme,setupComplete:true,screensaverMinutes:0,location:{name:'Old place',latitude:1,longitude:2}},network:{},bluetooth:{devices:[],prompts:[]},audio:{},player:{},weather:{}};const queries:string[]=[];
await page.route('**/api/**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/api/geocode'){queries.push(url.searchParams.get('q')!);if(queries.length===1){await route.fulfill({status:503,json:{error:'geocode_unavailable'}});return;}await route.fulfill({json:{results:[{name:'București · Sector 5',latitude:44.4,longitude:26.07}]}});return;}await route.fulfill({json:url.pathname==='/api/session'?{token:'fixture'}:url.pathname==='/api/state'?state:{ok:true}});});
await page.goto('/');await page.locator('.main-nav button').nth(3).tap();await page.locator('.settings-tabs button').filter({hasText:lang==='ro'?'Vreme':'Weather'}).tap();await page.getByRole('button',{name:'Old place',exact:true}).tap();await page.locator('.keyboard-card').getByRole('button',{name:lang==='ro'?'Aplică':'Apply',exact:true}).tap();await expect(page.locator('.settings-panel').getByRole('alert')).toBeVisible();expect(queries).toEqual(['Old place']);await page.locator('.settings-panel').getByRole('alert').getByRole('button').tap();await expect(page.locator('.geo-item')).toHaveCount(1);expect(queries).toEqual(['Old place','Old place']);
});



test('Location accepted PATCH then failed state read reports backend error and retry never repeats PATCH',async({page},info)=>{
 const lang=info.project.name.endsWith('ro')?'ro':'en';let writes=0,failRead=false;const state:any={preferences:{language:lang,theme:'night',setupComplete:true,screensaverMinutes:1,location:{name:'Old place',latitude:1,longitude:2}},network:{},bluetooth:{devices:[],prompts:[]},audio:{},player:{},weather:{}};
 await page.route('**/api/**',async r=>{const p=new URL(r.request().url()).pathname;if(p==='/api/preferences'){writes++;Object.assign(state.preferences,r.request().postDataJSON());failRead=true;await r.fulfill({json:state.preferences});return;}if(p==='/api/state'&&failRead){failRead=false;await r.fulfill({status:503,json:{error:'backend_unavailable'}});return;}await r.fulfill({json:p==='/api/session'?{token:'fixture'}:p==='/api/state'?state:p==='/api/geocode'?{results:[{name:'Sector 5',latitude:44.4,longitude:26.07}]}:{ok:true}});});
 await page.goto('/');await page.locator('.main-nav button').nth(3).tap();await page.locator('.settings-tabs button').filter({hasText:lang==='ro'?'Vreme':'Weather'}).tap();await page.getByRole('button',{name:'Old place',exact:true}).tap();await page.locator('.keyboard-card').getByRole('button',{name:lang==='ro'?'Aplică':'Apply',exact:true}).tap();await page.locator('.geo-item').first().tap();await expect(page.getByRole('button',{name:'Sector 5',exact:true})).toBeVisible();await expect(page.locator('.geo-item')).toHaveCount(0);await expect(page.locator('.settings-panel').getByRole('alert')).toHaveCount(0);await expect(page.locator('.error-strip')).toBeVisible();expect(writes).toBe(1);await page.locator('.error-strip').getByRole('button',{name:lang==='ro'?'Încearcă din nou':'Try again',exact:true}).tap();await expect(page.locator('.error-strip')).toHaveCount(0);expect(writes).toBe(1);
});
