import {test,expect} from '@playwright/test';
for(const theme of ['ink','night'])test(`decorative settings persist and govern the real sky ${theme}`,async({page},info)=>{
 test.setTimeout(60000);const ro=info.project.name.endsWith('ro');let fail=false;
 const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,nightEnabled:false,screensaverMinutes:1,navigationCollapsed:false,visualizerStyle:'wave',location:{name:'București, Sectorul 5',latitude:44.4,longitude:26.07}},network:{state:'connected'},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'playing',kind:'radio',station_name:'Station',url:'https://example.org/stream'},weather:{current:{temperature_c:13,weather_code:0,is_day:0},daily:[],stale:false}};
 await page.addInitScript(()=>{crypto.getRandomValues=((array:Uint32Array)=>{array.fill(0);return array;}) as typeof crypto.getRandomValues;});
 await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;let json:any={ok:true};if(path==='/api/session')json={token:'fixture'};else if(path==='/api/state')json=state;else if(path==='/api/preferences'){if(fail)return route.fulfill({status:500,json:{error:'save_failed'}});Object.assign(state.preferences,route.request().postDataJSON());json=state.preferences;}else if(path==='/api/audio/visualization')json={available:true,status:'ready',waveform:Array.from({length:64},(_,i)=>Math.sin(i)*.4),bars:Array(16).fill(.3),peak:.4,rms:.2,silent:false};await route.fulfill({json});});
 await page.clock.install({time:new Date('2026-10-04T23:00:00Z')});await page.goto('/');
 const settings=async()=>{await page.locator('.main-nav button').nth(3).tap();await page.locator('.settings-tabs button').filter({hasText:ro?'Acasă':'Home'}).tap();};
 const aircraft=page.getByRole('button',{name:ro?'Avioane decorative':'Decorative aircraft',exact:true}),dust=page.getByRole('button',{name:ro?'Praf lunar decorativ':'Decorative lunar dust',exact:true});
 await settings();await aircraft.scrollIntoViewIfNeeded();await expect(aircraft).toHaveAttribute('aria-pressed','true');await expect(dust).toHaveAttribute('aria-pressed','false');
 for(const button of [aircraft,dust]){const box=(await button.boundingBox())!;expect(box.width).toBeGreaterThanOrEqual(48);expect(box.height).toBeGreaterThanOrEqual(48);}
 await aircraft.tap();await expect(aircraft).toHaveAttribute('aria-pressed','false');await dust.scrollIntoViewIfNeeded();await dust.tap();await expect(dust).toHaveAttribute('aria-pressed','true');
 await expect(page.locator('.settings-panel')).toContainText(ro?'nu trafic aerian sau impacturi reale':'not live air traffic or real impacts');await page.screenshot({path:info.outputPath(`ambient-settings-${theme}.png`)});
 await page.reload();await settings();await aircraft.scrollIntoViewIfNeeded();await expect(aircraft).toHaveAttribute('aria-pressed','false');await expect(dust).toHaveAttribute('aria-pressed','true');
 fail=true;await dust.scrollIntoViewIfNeeded();await dust.tap();await expect(page.locator('.error-strip')).toBeVisible();await expect(dust).toHaveAttribute('aria-pressed','true');expect(state.preferences.decorativeLunarDust).toBe(true);fail=false;
 await page.locator('.main-nav button').nth(0).tap();await page.clock.runFor(65020);await expect(page.locator('[data-ambient-event=aircraft]')).toHaveCount(0);await expect(page.locator('[data-ambient-event=lunar-dust]')).toHaveCount(1);
 await expect(page.locator('.app')).toHaveAttribute('data-home-phase','ambient');await expect(page.locator('.pysh-screensaver')).toHaveCount(0);const phase=await page.locator('.ambient-moon').getAttribute('data-lunar-illumination');expect(Number(phase)).toBeGreaterThan(0);expect(Number(phase)).toBeLessThan(1);
 await page.locator('.ambient-lunar-event').evaluate(el=>el.getAnimations({subtree:true}).forEach(animation=>{animation.currentTime=500;animation.pause();}));await page.screenshot({path:info.outputPath(`ambient-home-dust-${theme}.png`)});
 // Wake consumes the first touch, then explicitly navigate to the settings.
 await page.locator('.app').tap({position:{x:400,y:250}});await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');await settings();await aircraft.scrollIntoViewIfNeeded();await aircraft.tap();await dust.scrollIntoViewIfNeeded();await dust.tap();await expect(dust).toHaveAttribute('aria-pressed','false');
 await page.locator('.main-nav button').nth(0).tap();await page.clock.runFor(18020);await expect(page.locator('[data-ambient-event=aircraft]')).toHaveCount(1);await expect(page.locator('[data-ambient-event=lunar-dust]')).toHaveCount(0);await expect(page.locator('.ambient-moon')).toHaveAttribute('data-lunar-illumination',phase!);
 await page.locator('.ambient-flight').evaluate(el=>el.getAnimations().forEach(animation=>{animation.currentTime=12000;animation.pause();}));await page.screenshot({path:info.outputPath(`ambient-home-aircraft-${theme}.png`)});
});
