import {test,expect,type Page} from '@playwright/test';
async function fixture(page:Page,lang:string,theme:string){
 const actions:any[]=[],positions={weather:{x:.14,y:.18},forecast:{x:.34,y:.6},playback:{x:.2,y:.79},visualizer:{x:.4,y:.72}};
 const state:any={preferences:{language:lang,theme,setupComplete:true,nightEnabled:false,screensaverMinutes:1,visualizerStyle:'wave',homeCards:['weather','forecast','playback'],homePositions:positions,timezone:'Europe/Bucharest',favorites:[],shortcuts:['radio','media']},network:{state:'connected'},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:40,mute:false},player:{state:'playing',kind:'radio',url:'https://example.org/radio',station_name:'Fixture Radio'},weather:{stale:false,current:{temperature_c:13,weather_code:0,is_day:0},daily:Array.from({length:5},(_,i)=>({date:`2026-10-0${i+4}`,weather_code:0,max_c:20,min_c:10}))}};
 await page.route('**/api/**',async r=>{const path=new URL(r.request().url()).pathname;let json:any={ok:true};if(r.request().method()!=='GET')actions.push({path,body:r.request().postDataJSON()});if(path==='/api/session')json={token:'fixture'};if(path==='/api/state')json=state;if(path==='/api/preferences'){Object.assign(state.preferences,r.request().postDataJSON());json=state.preferences;}if(path==='/api/audio/visualization')json={available:true,status:'ready',waveform:Array(64).fill(.3),bars:Array(16).fill(.3),rms:.3,peak:.3,silent:false};if(path==='/api/radio')json={stations:[]};await r.fulfill({json});});
 await page.clock.install();await page.goto('/');await expect(page.locator('.ambient-home')).toBeVisible();return {state,actions,positions};
}
for(const theme of ['ink','night']){
 test(`Home ambient after30s preserves clock/signal/positions and first touch only wakes in ${theme}`,async({page},info)=>{
 const f=await fixture(page,info.project.name.endsWith('ro')?'ro':'en',theme),saved=JSON.stringify(f.state.preferences.homePositions);const initialSignal=await page.locator('.ambient-visualizer').boundingBox();
 const button=await page.locator('.playback-toggle').boundingBox();await page.clock.fastForward(120000);
 await expect(page.locator('.app')).toHaveAttribute('data-home-phase','ambient');await expect(page.locator('.pysh-screensaver')).toHaveCount(0);await expect(page.locator('.top-clock')).toBeVisible();await expect(page.locator('.ambient-visualizer svg')).toBeVisible();
 for(const selector of ['.rail','.topbar-title','.date-label','.topbar-right','.ambient-weather','.ambient-forecast','.ambient-dock','.signal-station'])await expect(page.locator(selector)).toBeHidden();
 const ambientSignal=await page.locator('.ambient-visualizer').boundingBox();expect(ambientSignal?.x).toBe(initialSignal?.x);expect(JSON.stringify(f.state.preferences.homePositions)).toBe(saved);
 const before=f.actions.length;await page.touchscreen.tap(button!.x+button!.width/2,button!.y+button!.height/2);await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');expect(f.actions.length).toBe(before);await expect(page.locator('.topbar')).not.toHaveClass(/topbar-idle/);
 await expect(page.locator('.ambient-weather')).toHaveClass(/card-compact/);await expect(page.locator('.ambient-forecast')).toHaveClass(/card-compact/);await expect(page.locator('.ambient-dock')).toHaveClass(/card-compact/);await expect(page.locator('.rail')).toBeVisible();
 expect(JSON.stringify(f.state.preferences.homePositions)).toBe(saved);expect(f.actions.filter(a=>a.path==='/api/preferences')).toEqual([]);
 await page.clock.fastForward(31000);await page.keyboard.press('Space');await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');await page.locator('.playback-toggle').evaluate(el=>el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,detail:0})));expect(f.actions.length).toBe(before);await expect(page.locator('.topbar')).not.toHaveClass(/topbar-idle/);await page.clock.fastForward(11000);await expect(page.locator('.topbar')).toHaveClass(/topbar-idle/);
 await page.screenshot({path:info.outputPath(`ambient-home-woken-${theme}.png`)});await page.locator('.ambient-visualizer').tap();await expect(page.locator('.playback-toggle')).toBeVisible();await page.locator('.playback-toggle').tap();expect(f.actions.at(-1)?.path).toBe('/api/player');
 });
 test(`Home modal/BT prompt suspend ambient; settings choice and other page screensaver work in ${theme}`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro'),f=await fixture(page,ro?'ro':'en',theme);
 await page.locator('.topbar-right .icon-button').tap();await page.clock.fastForward(120000);await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');await expect(page.locator('.pysh-screensaver')).toHaveCount(0);await page.getByRole('dialog').getByRole('button',{name:ro?'Închide':'Close',exact:true}).tap();
 f.state.bluetooth.prompts=[{id:'one',kind:'confirmation',name:'Fixture speaker',value:'123456'}];await page.clock.runFor(2600);await page.clock.fastForward(31000);await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');f.state.bluetooth.prompts=[];await page.clock.runFor(2600);
 await page.locator('.main-nav button').nth(3).tap();const trigger=page.getByRole('button',{name:ro?'Vizualizare audio':'Audio visualization',exact:true});await trigger.scrollIntoViewIfNeeded();await trigger.tap();await page.clock.fastForward(120000);await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('.pysh-screensaver')).toHaveCount(0);await page.getByRole('dialog').getByRole('button',{name:ro?'Închide':'Close',exact:true}).tap();
 await page.clock.runFor(62000);await expect(page.locator('.pysh-screensaver')).toBeVisible();await page.locator('.saver-home').tap();await expect(page.locator('.pysh-screensaver')).toHaveCount(0);
 const preview=page.getByRole('button',{name:ro?'Previzualizează repausul':'Preview screensaver',exact:true});await preview.scrollIntoViewIfNeeded();await preview.tap();await expect(page.locator('.pysh-screensaver')).toBeVisible();
 });
}
test('Home reduced-motion ambient transition keeps only clock/signal and keyboard wake is consumed',async({page},info)=>{
 await page.emulateMedia({reducedMotion:'reduce'});const f=await fixture(page,info.project.name.endsWith('ro')?'ro':'en','night');await page.locator('.playback-toggle').focus();await page.clock.fastForward(31000);await expect(page.locator('.app')).toHaveAttribute('data-home-phase','ambient');await expect(page.locator('.top-clock')).toBeVisible();await expect(page.locator('.ambient-visualizer')).toBeVisible();await page.keyboard.press('Enter');await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');await page.locator('.playback-toggle').evaluate(el=>el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,detail:0})));expect(f.actions).toEqual([]);await expect(page.locator('.topbar')).not.toHaveClass(/topbar-idle/);
});
