import {test,expect} from '@playwright/test';
for(const theme of ['ink','night'])test(`Home ${theme}: cross-row swapping and deliberate overlap survive saving`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro');
 const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,nightEnabled:false,navigationCollapsed:false,navigationAutoHide:false,screensaverMinutes:0,visualizerStyle:'wave',visualizerSize:'compact',homeCards:['weather','forecast','playback'],homePositions:{},timezone:'Europe/Bucharest',shortcuts:['radio','media']},network:{state:'connected'},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'playing',kind:'radio',station_name:'Radio One',url:'https://example.org/stream'},weather:{current:{temperature_c:13,weather_code:2,is_day:0,feels_like_c:11},daily:Array.from({length:5},(_,i)=>({date:`2026-10-0${i+3}`,weather_code:0,max_c:22,min_c:11})),stale:false}};
 await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;let json:any={ok:true};if(path==='/api/session')json={token:'fixture'};else if(path==='/api/state')json=state;else if(path==='/api/preferences'){Object.assign(state.preferences,route.request().postDataJSON());json=state.preferences;}else if(path==='/api/audio/visualization')json={available:true,status:'ready',waveform:Array(64).fill(.2),bars:Array(16).fill(.3),peak:.3,rms:.2,silent:false};await route.fulfill({json});});
 await page.goto('/');await expect(page.locator('.ambient-weather')).toBeVisible();
 await page.locator('.main-nav button').nth(3).tap();await page.locator('.settings-tabs button').filter({hasText:ro?'Acasă':'Home'}).tap();await page.getByRole('button',{name:ro?'Aranjează Acasă':'Arrange Home',exact:true}).tap();
 const cards={weather:page.locator('.ambient-weather'),forecast:page.locator('.ambient-forecast'),visualizer:page.locator('.ambient-visualizer'),playback:page.locator('.ambient-dock')};
 const choose=async(key:keyof typeof cards)=>{await page.getByRole('button',{name:ro?'Selectează cardul':'Choose card',exact:true}).tap();const label=key==='weather'?(ro?'Vreme':'Weather'):key==='forecast'?(ro?'Prognoză':'Forecast'):key==='visualizer'?(ro?'Vizualizator':'Visualizer'):(ro?'În redare':'Now playing');await page.getByRole('dialog').getByRole('radio',{name:label,exact:true}).tap();};
 const drag=async(key:keyof typeof cards,x:number,y:number)=>{await choose(key);const card=(await cards[key].boundingBox())!,grip=(await page.locator(`[data-layout-handle=${key}]`).boundingBox())!;await page.mouse.move(grip.x+24,grip.y+24);await page.mouse.down();await page.mouse.move(grip.x+24+x-card.x,grip.y+24+y-card.y,{steps:12});await page.mouse.up();await expect.poll(async()=>Math.abs((await cards[key].boundingBox())!.y-y)).toBeLessThan(2);await expect.poll(async()=>Math.abs((await cards[key].boundingBox())!.x-x)).toBeLessThan(2);};
 const w=(await cards.weather.boundingBox())!,f=(await cards.forecast.boundingBox())!;
 const root=(await page.locator('.ambient-home').boundingBox())!,upperY=root.y+12,lowerY=root.y+root.height-w.height-12;await drag('weather',w.x,lowerY);await drag('forecast',f.x,upperY);
 expect((await cards.weather.boundingBox())!.y-(await cards.forecast.boundingBox())!.y).toBeGreaterThan(100);
 await drag('forecast',w.x,lowerY); // intentionally overlaps weather; no collision avoidance
 const assertOverlap=async()=>{const a=(await cards.weather.boundingBox())!,b=(await cards.forecast.boundingBox())!;const left=Math.max(a.x,b.x),top=Math.max(a.y,b.y),right=Math.min(a.x+a.width,b.x+b.width),bottom=Math.min(a.y+a.height,b.y+b.height);expect(right-left).toBeGreaterThan(80);expect(bottom-top).toBeGreaterThan(30);expect(await page.evaluate(({x,y})=>Boolean(document.elementFromPoint(x,y)?.closest('.ambient-forecast')),{x:(left+right)/2,y:(top+bottom)/2})).toBe(true);};
 // Compact cards deliberately share a top-left point while being arranged.
 expect(Math.abs((await cards.weather.boundingBox())!.y-(await cards.forecast.boundingBox())!.y)).toBeLessThan(2);expect(Math.abs((await cards.weather.boundingBox())!.x-(await cards.forecast.boundingBox())!.x)).toBeLessThan(2);
 await assertOverlap();await choose('weather');await expect(cards.weather).toHaveCSS('z-index','5');await choose('forecast');
 const before={weather:(await cards.weather.boundingBox())!,forecast:(await cards.forecast.boundingBox())!};
 await page.getByRole('button',{name:ro?'Gata':'Done',exact:true}).tap();expect(state.preferences.homePositions.forecast.z).toBe(4);expect(state.preferences.homePositions.weather.z).toBeLessThan(4);
 await page.reload();await expect(cards.forecast).toBeVisible();
 // Reload expands cards. Their anchored edge, not necessarily their top-left,
 // must survive growth, and the deliberate overlap/stacking must still hold.
 for(const key of ['weather','forecast'] as const){const saved=state.preferences.homePositions[key],original=before[key];const horizontal=(r:typeof original)=>saved.anchorX==='right'?r.x+r.width:r.x,vertical=(r:typeof original)=>saved.anchorY==='bottom'?r.y+r.height:r.y;await expect.poll(async()=>Math.abs(horizontal((await cards[key].boundingBox())!)-horizontal(original))).toBeLessThan(2);await expect.poll(async()=>Math.abs(vertical((await cards[key].boundingBox())!)-vertical(original))).toBeLessThan(2);}
 await assertOverlap();await page.screenshot({path:info.outputPath(`free-overlap-${theme}.png`)});
});
