import {test,expect} from '@playwright/test';
for(const theme of ['ink','night'])for(const size of ['compact','balanced','large'])test(`First Arrange ${theme} ${size}: all compact unpositioned cards and grips fit without overlap`,async({page},info)=>{
 const lang=info.project.name.endsWith('ro')?'ro':'en',writes:any[]=[];const state={preferences:{language:lang,theme,setupComplete:true,nightEnabled:false,navigationCollapsed:false,navigationAutoHide:false,screensaverMinutes:0,decorativeAircraft:false,decorativeLunarDust:false,visualizerStyle:'wave',visualizerSize:size,homeCards:['weather','forecast','playback'],homePositions:{},location:{name:'București · Sector 5',latitude:44.4,longitude:26.07}},network:{},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false,outputs:[]},player:{state:'playing',kind:'radio',station_name:'Test radio',title:'Artist · Song',url:'https://example.org/stream'},weather:{current:{temperature_c:8,weather_code:0,is_day:0,feels_like_c:5},daily:Array.from({length:5},(_,i)=>({date:`2026-10-0${i+4}`,weather_code:i?2:0,max_c:24+i,min_c:4+i})),stale:false,updated_at:new Date().toISOString()}};
 await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;if(route.request().method()!=='GET')writes.push({path,body:route.request().postDataJSON()});return route.fulfill({json:path==='/api/session'?{token:'fixture'}:path==='/api/state'?state:path==='/api/audio/visualization'?{available:true,status:'ready',waveform:Array.from({length:64},(_,i)=>Math.sin(i*.7)*.2),bars:Array(16).fill(.2),rms:.2,peak:.3,silent:false}:{ok:true}});});
 await page.goto('/');await page.locator('.main-nav button').nth(3).tap();await page.locator('.settings-tabs button').filter({hasText:lang==='ro'?'Acasă':'Home'}).tap();await page.getByRole('button',{name:lang==='ro'?'Aranjează Acasă':'Arrange Home',exact:true}).tap();await expect(page.locator('.ambient-home')).toHaveAttribute('data-layout-editing','true');await expect(page.locator('.home-drag-handle')).toHaveCount(4);
 const geometry=await page.evaluate(()=>{const canvas=document.querySelector('.ambient-home')!.getBoundingClientRect();const cards=[...document.querySelectorAll('.home-drag-handle')].map(handle=>{const card=handle.parentElement!,b=card.getBoundingClientRect(),h=handle.getBoundingClientRect();return {key:handle.getAttribute('data-layout-handle'),box:b.toJSON(),grip:h.toJSON(),positioned:card.getAttribute('data-home-positioned'),compact:card.classList.contains('card-compact'),hit:handle.contains(document.elementFromPoint(h.x+h.width/2,h.y+h.height/2)),bounds:b.left>=canvas.left-1&&b.top>=canvas.top-1&&b.right<=canvas.right+1&&b.bottom<=canvas.bottom+1,gripBounds:h.left>=canvas.left&&h.top>=canvas.top&&h.right<=canvas.right&&h.bottom<=canvas.bottom};});const sources=[...document.querySelectorAll('.ambient-home .weather-source a')].map(a=>{const b=a.getBoundingClientRect();return {width:b.width,height:b.height,hit:a.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2))};});return {cards,sources};});
 for(const c of geometry.cards){expect(c.positioned,c.key!).toBe('false');expect(c.bounds,c.key!).toBe(true);expect(c.gripBounds,c.key!).toBe(true);expect(c.hit,c.key!).toBe(true);expect(c.grip.width).toBeCloseTo(48,2);expect(c.grip.height).toBeCloseTo(48,2);if(c.key!=='visualizer')expect(c.compact,c.key!).toBe(true);}expect(geometry.cards.find(c=>c.key==='visualizer')!.box.height).toBeCloseTo({compact:64,balanced:88,large:112}[size],2);
 for(let i=0;i<geometry.cards.length;i++)for(let j=i+1;j<geometry.cards.length;j++){const a=geometry.cards[i].box,b=geometry.cards[j].box,area=Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));expect(area,`${geometry.cards[i].key}/${geometry.cards[j].key}`).toBeLessThanOrEqual(1);}
 const location=await page.locator('.weather-location').evaluate(el=>{const range=document.createRange();range.selectNodeContents(el);const full=range.getBoundingClientRect(),visible=el.getBoundingClientRect();return {text:el.textContent,full:full.toJSON(),visible:visible.toJSON(),scroll:el.scrollHeight,client:el.clientHeight};});expect(location.text).toBe('București · Sector 5');expect(location.scroll).toBeLessThanOrEqual(location.client+1);expect(location.full.bottom).toBeLessThanOrEqual(location.visible.bottom+1);expect(location.full.right).toBeLessThanOrEqual(location.visible.right+1);expect(geometry.sources).toHaveLength(0);for(const s of geometry.sources){expect(s.width).toBeGreaterThanOrEqual(47.99);expect(s.height).toBeGreaterThanOrEqual(47.99);expect(s.hit).toBe(true);}expect(writes).toEqual([]);expect(state.preferences.homePositions).toEqual({});await page.screenshot({path:info.outputPath(`initial-arrange-${theme}-${size}.png`)});
});
