import {test,expect} from '@playwright/test';
const messages:any={stream_failed:['This file could not be played.','Acest fișier nu a putut fi redat.'],player_timeout:['The player did not respond in time.','Playerul nu a răspuns la timp.'],player_disconnected:['Playback was disconnected.','Redarea s-a deconectat.'],player_failed:['The player could not start.','Playerul nu a putut porni.'],unknown:['Playback could not continue.','Redarea nu a putut continua.']};
for(const theme of ['ink','night'])for(const reason of Object.keys(messages))test(`local audio notice ${theme} ${reason}`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro'),file='Recording with a meaningful long file name.wav',path='/approved/album/'+file;const actions:any[]=[];const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,screensaverMinutes:0,nightEnabled:false},network:{},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'error',kind:'audio',url:path,title:file,error:reason==='unknown'?'RAW_PRIVATE_DECODER_LOG':reason,canNext:true,canPrevious:true},weather:{}};
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());let json:any={ok:true};if(u.pathname==='/api/session')json={token:'fixture'};else if(u.pathname==='/api/state')json=state;else if(u.pathname==='/api/media')json={path:'/approved',items:[{name:file,path,kind:'audio'},{name:'Healthy.wav',path:'/approved/Healthy.wav',kind:'audio'}]};else if(route.request().method()==='POST'){const body=route.request().postDataJSON();actions.push({path:u.pathname,body});if(u.pathname==='/api/play')state.player={state:'playing',kind:'audio',url:body.path,title:body.title,position:1,duration:300};}await route.fulfill({json});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();const notice=page.locator('.local-audio-recovery');await expect(notice).toBeVisible();await expect(notice).toContainText(file);await expect(notice).toContainText(messages[reason][ro?1:0]);await expect(notice).toContainText(ro?'Reîncearcă redarea sau alege alt fișier.':'Replay or choose another file.');await expect(page.locator('body')).not.toContainText('RAW_PRIVATE_DECODER_LOG');await expect(page.locator('.error-strip')).toHaveCount(0);const replay=notice.getByRole('button',{name:ro?'Reia redarea':'Replay',exact:true});const box=await replay.boundingBox();expect(box!.height).toBeGreaterThanOrEqual(48);expect(box!.width).toBeGreaterThanOrEqual(48);expect(box!.x+box!.width).toBeLessThanOrEqual(800);expect(box!.y+box!.height).toBeLessThanOrEqual(480);await expect(page.getByRole('button',{name:'Healthy.wav',exact:false})).toBeEnabled();await expect(page.locator('.local-audio-bar').getByRole('button',{name:ro?'Următor':'Next',exact:true})).toBeEnabled();await page.screenshot({path:info.outputPath('audio-error-notice.png')});await page.locator('.local-audio-bar').getByRole('button',{name:ro?'Următor':'Next',exact:true}).tap();await expect.poll(()=>actions.length).toBe(1);expect(actions[0]).toEqual({path:'/api/player',body:{action:'next'}});await replay.tap();await expect.poll(()=>actions.length).toBe(2);expect(actions[1]).toEqual({path:'/api/play',body:{source:'local',path,title:file}});await expect(notice).toHaveCount(0);await page.getByRole('button',{name:'Healthy.wav',exact:false}).tap();await expect.poll(()=>actions.length).toBe(3);expect(actions[2].body.path).toBe('/approved/Healthy.wav');await page.locator('.main-nav button').first().tap();await expect(page.locator('.ambient-home')).toBeVisible();
});

for(const theme of ['ink','night'])test(`local audio notice ${theme} replay failure ownership and radio isolation`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro'),file='Unavailable.wav',path='/approved/'+file;let release!:()=>void,pending=false,attempts=0;const gate=new Promise<void>(r=>release=r),actions:any[]=[];const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,screensaverMinutes:0,nightEnabled:false},network:{},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'error',kind:'audio',url:path,title:file,error:'stream_failed'},weather:{}};
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());let json:any={ok:true};if(u.pathname==='/api/session')json={token:'fixture'};else if(u.pathname==='/api/state')json=state;else if(u.pathname==='/api/media')json={path:'/approved',items:[{name:'Healthy.wav',path:'/approved/Healthy.wav',kind:'audio'}]};else if(u.pathname==='/api/play'){const body=route.request().postDataJSON();actions.push({path:u.pathname,body});attempts++;if(attempts===1){pending=true;await gate;return route.fulfill({status:409,json:{error:'media_not_found'}});}state.player={state:'playing',kind:'audio',url:body.path,title:body.title,position:1,duration:100};}await route.fulfill({json});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();await page.locator('.local-audio-recovery').getByRole('button',{name:ro?'Reia redarea':'Replay'}).tap();await expect.poll(()=>pending).toBe(true);await expect(page.locator('.local-audio-recovery')).toHaveCount(0);release();await expect(page.locator('.error-strip')).toBeVisible();await expect(page.locator('.local-audio-recovery')).toHaveCount(0);await page.locator('.error-strip').getByRole('button',{name:ro?'Încearcă din nou':'Try again',exact:true}).tap();await expect.poll(()=>actions.length).toBe(2);expect(actions[0]).toEqual(actions[1]);expect(actions[1].body).toEqual({source:'local',path,title:file});await expect(page.locator('.error-strip')).toHaveCount(0);state.player={state:'error',kind:'radio',url:'https://fixture.invalid/radio',title:'Radio fixture',error:'RAW_PRIVATE_DECODER_LOG'};await expect(page.locator('.local-audio-bar')).toHaveCount(0,{timeout:5000});await expect(page.locator('.local-audio-recovery')).toHaveCount(0);await expect(page.locator('body')).not.toContainText('RAW_PRIVATE_DECODER_LOG');await expect(page.getByRole('button',{name:'Healthy.wav',exact:false})).toBeEnabled();
});
