import {test,expect} from '@playwright/test';
for(const theme of ['ink','night'])for(const first of ['video','audio'])for(const outcome of ['reject','accept'])test(`selection ownership ${theme} ${first} ${outcome} replaced listing`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro');let release!:()=>void,pending=false,attempts=0,lists=0;const gate=new Promise<void>(r=>release=r),actions:any[]=[];const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,screensaverMinutes:0,nightEnabled:false},network:{},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'idle'},weather:{}};
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());let json:any={ok:true};if(u.pathname==='/api/session')json={token:'fixture'};else if(u.pathname==='/api/state')json=state;else if(u.pathname==='/api/media'){lists++;json={path:lists===1?'/original':'/replacement',items:lists===1?[{name:'Original.webm',path:'/original/Original.webm',kind:'video'},{name:'Original.wav',path:'/original/Original.wav',kind:'audio'}]:[{name:'Replacement.wav',path:'/replacement/Replacement.wav',kind:'audio'}]};}else if(u.pathname==='/api/media/file')return route.fulfill({contentType:'video/webm',body:''});else if(route.request().method()==='POST'){const body=route.request().postDataJSON();actions.push({path:u.pathname,body});if(u.pathname==='/api/player'||u.pathname==='/api/play'){attempts++;if(attempts===1){pending=true;await gate;if(outcome==='reject')return route.fulfill({status:409,json:{error:'media_not_found'}});}if(u.pathname==='/api/play')state.player={state:'playing',kind:'audio',url:body.path,title:body.title,position:1,duration:300};}}await route.fulfill({json});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();await page.getByRole('button',{name:first==='video'?'Original.webm':'Original.wav',exact:false}).tap();await expect.poll(()=>pending).toBe(true);
 await page.locator('.main-nav button').nth(0).tap();await expect(page.locator('.ambient-home')).toBeVisible();await page.locator('.main-nav button').nth(2).tap();await expect(page.getByRole('button',{name:'Replacement.wav',exact:false})).toBeVisible();release();await page.waitForTimeout(250);await expect(page.locator('.video-overlay')).toHaveCount(0);await expect(page.locator('.error-strip')).toHaveCount(0);await expect(page.getByRole('button',{name:'Replacement.wav',exact:false})).toBeEnabled();expect(actions).toHaveLength(1);
 // Next explicit intent succeeds. Old payload cannot reappear in Retry or execute automatically.
 await page.getByRole('button',{name:'Replacement.wav',exact:false}).tap();await expect.poll(()=>actions.length).toBe(2);expect(actions[1]).toEqual({path:'/api/play',body:{source:'local',path:'/replacement/Replacement.wav',title:'Replacement.wav'}});await expect(page.locator('.local-audio-bar')).toBeVisible();
});

for(const theme of ['ink','night'])for(const first of ['video','audio'])test(`queued selection ${theme} ${first} abandoned before backend launch`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro');let release!:()=>void,pending=false,lists=0;const gate=new Promise<void>(r=>release=r),actions:any[]=[];const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,screensaverMinutes:0,nightEnabled:false},network:{},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'playing',kind:'audio',url:'/old/Playing.wav',title:'Playing.wav',position:1,duration:300},weather:{}};
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());let json:any={ok:true};if(u.pathname==='/api/session')json={token:'fixture'};else if(u.pathname==='/api/state')json=state;else if(u.pathname==='/api/media'){lists++;json={path:lists===1?'/original':'/replacement',items:lists===1?[{name:'Original.webm',path:'/original/Original.webm',kind:'video'},{name:'Original.wav',path:'/original/Original.wav',kind:'audio'}]:[{name:'Replacement.wav',path:'/replacement/Replacement.wav',kind:'audio'}]};}else if(route.request().method()==='POST'){const body=route.request().postDataJSON();actions.push({path:u.pathname,body});if(u.pathname==='/api/player'&&body.action==='pause'){pending=true;await gate;state.player={...state.player,state:'paused'};}if(u.pathname==='/api/play')state.player={state:'playing',kind:'audio',url:body.path,title:body.title,position:1,duration:300};}await route.fulfill({json});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();await page.locator('.local-audio-bar').getByRole('button',{name:ro?'Pauză':'Pause',exact:true}).tap();await expect.poll(()=>pending).toBe(true);await page.getByRole('button',{name:first==='video'?'Original.webm':'Original.wav',exact:false}).tap();await expect(page.locator('.media-library')).toHaveAttribute('aria-busy','true');await page.locator('.main-nav button').nth(0).tap();await page.locator('.main-nav button').nth(2).tap();await expect(page.getByRole('button',{name:'Replacement.wav',exact:false})).toBeVisible();release();await expect(page.locator('.media-library')).toHaveAttribute('aria-busy','false');await page.waitForTimeout(200);expect(actions).toEqual([{path:'/api/player',body:{action:'pause'}}]);await expect(page.locator('.video-overlay')).toHaveCount(0);await expect(page.locator('.error-strip')).toHaveCount(0);await page.getByRole('button',{name:'Replacement.wav',exact:false}).tap();await expect.poll(()=>actions.length).toBe(2);expect(actions[1]).toEqual({path:'/api/play',body:{source:'local',path:'/replacement/Replacement.wav',title:'Replacement.wav'}});
});
