import {test,expect} from '@playwright/test';
for(const theme of ['ink','night'])for(const first of ['video','audio'])for(const fail of [false,true])test(`local selection ${theme} ${first} pending ${fail?'failure retry':'success'}`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro');let release!:()=>void,pending=false;const gate=new Promise<void>(r=>release=r),actions:any[]=[];let attempts=0;const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,screensaverMinutes:0,nightEnabled:false},network:{},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'idle'},weather:{}};
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());let json:any={ok:true};if(u.pathname==='/api/session')json={token:'fixture'};else if(u.pathname==='/api/state')json=state;else if(u.pathname==='/api/media')json={path:'/approved',items:[{name:'Film.webm',path:'/approved/Film.webm',kind:'video'},{name:'Music.wav',path:'/approved/Music.wav',kind:'audio'}]};else if(u.pathname==='/api/media/file')return route.fulfill({contentType:'video/webm',body:''});else if(route.request().method()==='POST'){const body=route.request().postDataJSON();actions.push({path:u.pathname,body});if(u.pathname==='/api/player'||u.pathname==='/api/play'){attempts++;if(attempts===1){pending=true;await gate;if(fail)return route.fulfill({status:409,json:{error:first==='video'?'playback_command_failed':'media_not_found'}});}if(u.pathname==='/api/play')state.player={state:'playing',kind:'audio',url:body.path,title:body.title,duration:300,position:1};}}await route.fulfill({json});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();
 // Two actual DOM click events in one JS task, before awaiting a render or request.
 await page.evaluate(first=>{const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('.media-item'));const a=buttons.find(b=>b.textContent?.includes(first==='video'?'Film.webm':'Music.wav'))!,b=buttons.find(b=>b!==a)!;a.click();b.click();a.click();},first);
 await expect.poll(()=>pending).toBe(true);const pendingState={busy:await page.locator('.media-library').getAttribute('aria-busy'),feedback:await page.getByRole('status').filter({hasText:ro?'Se deschide fișierul…':'Opening media…'}).count(),buttons:await page.locator('.media-item').evaluateAll(els=>els.map(el=>({disabled:(el as HTMLButtonElement).disabled,height:el.getBoundingClientRect().height})))};
 // A queued choice is never replayed after accepted or rejected first action.
 release();await page.waitForTimeout(200);expect(actions).toHaveLength(1);expect(pendingState.busy).toBe('true');expect(pendingState.feedback).toBe(1);expect(pendingState.buttons.every(b=>b.disabled&&b.height>=48)).toBe(true);await expect(page.locator('.media-library')).toHaveAttribute('aria-busy','false');
 if(fail){await expect(page.locator('.video-overlay')).toHaveCount(0);await expect(page.locator('.error-strip')).toBeVisible();await page.locator('.error-strip').getByRole('button',{name:ro?'Încearcă din nou':'Try again',exact:true}).tap();await expect.poll(()=>actions.length).toBe(2);expect(actions[1]).toEqual(actions[0]);await expect(page.locator('.error-strip')).toHaveCount(0);}
 if(first==='video'){await expect(page.locator('.video-overlay')).toBeVisible();expect(actions.every(a=>a.path==='/api/player'&&a.body.action==='stop')).toBe(true);await page.locator('.video-back').tap();await expect(page.locator('.video-overlay')).toHaveCount(0);}else{await expect(page.locator('.video-overlay')).toHaveCount(0);await expect(page.locator('.local-audio-bar')).toBeVisible();expect(actions.every(a=>a.path==='/api/play'&&a.body.path==='/approved/Music.wav')).toBe(true);}
 await expect(page.getByRole('button',{name:'Film.webm',exact:false})).toBeEnabled();await expect(page.getByRole('button',{name:'Music.wav',exact:false})).toBeEnabled();await page.screenshot({path:info.outputPath('selection-recovered.png')});
});
