import {test,expect} from '@playwright/test';
for(const theme of ['ink','night'])for(const first of ['local','local-audio','external'])for(const result of ['accept','reject'])test(`media opening ownership ${theme} ${first} ${result}`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro');let release!:()=>void,pending=false;const gate=new Promise<void>(r=>release=r),actions:any[]=[];const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,screensaverMinutes:0,nightEnabled:false},network:{},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'idle'},weather:{}};
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());let json:any={ok:true};if(u.pathname==='/api/session')json={token:'fixture'};else if(u.pathname==='/api/state')json=state;else if(u.pathname==='/api/media')json={path:'/approved',items:[{name:'Film.webm',path:'/approved/Film.webm',kind:'video'},{name:'Music.wav',path:'/approved/Music.wav',kind:'audio'}]};else if(u.pathname==='/api/media/file')return route.fulfill({contentType:'video/webm',body:''});else if(route.request().method()==='POST'){const body=route.request().postDataJSON();actions.push({path:u.pathname,body});if(actions.length===1){pending=true;await gate;if(result==='reject')return route.fulfill({status:409,json:{error:first==='external'?'browser_unavailable':'playback_command_failed'}});}if(u.pathname==='/api/play')state.player={state:'playing',kind:'audio',url:body.path,title:body.title,duration:300,position:1};}await route.fulfill({json});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();await expect(page.locator('.media-item')).toHaveCount(2);
 // Admission must hold for real DOM clicks dispatched before the pending render.
 await page.evaluate(first=>{const local=Array.from(document.querySelectorAll<HTMLButtonElement>('.media-item')),service=Array.from(document.querySelectorAll<HTMLButtonElement>('.service-row')).find(b=>b.textContent?.includes('Netflix'))!;if(first!=='external'){local[first==='local'?0:1].click();service.click();service.click();}else{service.click();local[0].click();local[1].click();service.click();}},first);
 await expect.poll(()=>pending).toBe(true);if(first==='external'){await expect(page.locator('.service-panel')).toHaveAttribute('aria-busy','true');await expect(page.getByRole('status').filter({hasText:ro?'Se deschide serviciul…':'Opening service…'})).toBeVisible();}await expect(page.locator('.main-nav button').first()).toBeEnabled();const disabled={service:await page.locator('.service-row').first().isDisabled(),local:await page.locator('.media-item').first().isDisabled()};release();await page.waitForTimeout(250);expect(actions).toHaveLength(1);expect(disabled).toEqual({service:true,local:true});
 if(result==='reject'){await expect(page.locator('.error-strip')).toBeVisible();await page.locator('.error-strip').getByRole('button',{name:ro?'Închide':'Close',exact:true}).tap();}else if(first==='local'){await expect(page.locator('.video-overlay')).toBeVisible();await page.locator('.video-back').tap();}else await expect(page.locator('.video-overlay')).toHaveCount(0);
 await expect(page.locator('.service-row').first()).toBeEnabled();await expect(page.locator('.media-item').first()).toBeEnabled();await page.getByRole('button',{name:'Music.wav',exact:false}).tap();await expect.poll(()=>actions.length).toBe(2);expect(actions[1]).toEqual({path:'/api/play',body:{source:'local',path:'/approved/Music.wav',title:'Music.wav'}});await expect(page.locator('.local-audio-bar')).toBeVisible();
});
