import {test,expect} from '@playwright/test';
for(const theme of ['ink','night'])test(`Media sizes ${theme}`,async({page},info)=>{
const ro=info.project.name.endsWith('ro');const sizes:any[]=[[0,'0 B'],[999,'999 B'],[1000,'1 KB'],[1500,ro?'1,5 KB':'1.5 KB'],[999949,ro?'999,9 KB':'999.9 KB'],[999950,'1 MB'],[1000000,'1 MB'],[1500000,ro?'1,5 MB':'1.5 MB'],[1000000000,'1 GB'],[1234500000,ro?'1,2 GB':'1.2 GB'],['1000','1 KB'],[null,''],[undefined,''],['',''],['not bytes',''],[-1,''],[1.5,''],[true,''],[' 0 ',''],['12 MB',''],[Number.MAX_SAFE_INTEGER+1,'']];
const items=sizes.map(([size],i)=>({path:`/library/${i}.mp3`,name:i===0?'Very long recording name that remains reachable without pushing the size or arrow outside the list.mp3':`Recording ${i}.mp3`,kind:'audio',size}));items.push({path:'/library/folder',name:'Music folder',kind:'directory',size:1000});
const state:any={preferences:{language:ro?'ro':'en',theme,nightEnabled:false,setupComplete:true,screensaverMinutes:0,navigationCollapsed:false,navigationAutoHide:false},network:{},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'idle'},weather:{}};const attempts:any[]=[];let release!:()=>void;const held=new Promise<void>(r=>release=r);
await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/play'){attempts.push(route.request().postDataJSON());if(attempts.length===1){await held;return route.fulfill({status:500,json:{detail:'stream_failed'}});}return route.fulfill({json:{ok:true}});}return route.fulfill({json:path==='/api/session'?{token:'fixture'}:path==='/api/state'?state:path==='/api/media'?{path:'/library',parent:'',items}:{ok:true}});});
await page.goto('/');await page.locator('.main-nav button').nth(2).tap();await expect(page.locator('.media-item')).toHaveCount(items.length);
for(let i=0;i<sizes.length;i++){const row=page.locator('.media-item').nth(i);await row.scrollIntoViewIfNeeded();await expect(row.locator('small')).toHaveText(sizes[i][1]);const b=(await row.boundingBox())!,t=(await row.locator('b').boundingBox())!;expect(b.height).toBeGreaterThanOrEqual(48);expect(t.x+t.width).toBeLessThanOrEqual(b.x+b.width);}
await expect(page.locator('.media-item').last().locator('small')).toHaveText(ro?'Dosare':'Folders');const first=page.locator('.media-item').first();await first.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`sizes-${theme}.png`)});await first.tap();await expect(page.locator('.media-library')).toHaveAttribute('aria-busy','true');await expect(first).toBeDisabled();await expect(page.locator('.media-items [role=status]')).toContainText(ro?'Se deschide fișierul':'Opening media');release();await expect(page.locator('.error-strip')).toBeVisible();await expect(page.locator('.error-strip')).not.toContainText('stream_failed');await expect(first.locator('small')).toHaveText('0 B');await page.locator('.error-strip button').first().tap();await expect.poll(()=>attempts.length).toBe(2);expect(attempts[1]).toEqual(attempts[0]);await expect(first).toBeEnabled();await expect(page.locator('.error-strip')).toHaveCount(0);
});
