import {test,expect} from '@playwright/test';
for(const theme of ['ink','night'])for(const direction of ['folder','back'])for(const retry of ['inline','banner'])test(`Media ${theme} ${direction} failure ${retry} retry uses failed target`,async({page},info)=>{
 const lang=info.project.name.endsWith('ro')?'ro':'en',library='/library',folder='/library/Songs',album='/library/Songs/Album';const requested:string[]=[];let fail=true;
 const state={preferences:{language:lang,theme,setupComplete:true,screensaverMinutes:0},network:{},bluetooth:{devices:[],prompts:[]},audio:{},player:{},weather:{}};
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/api/media'){const target=u.searchParams.get('path')||'';requested.push(target);const failedTarget=direction==='folder'?folder:library;if(target===failedTarget&&fail){fail=false;await route.fulfill(direction==='folder'?{status:503,json:{error:'media_unavailable'}}:{json:{error:'media_unavailable'}});return;}const current=target||library;await route.fulfill({json:{path:current,parent:current===folder?library:'',items:current===library?[{name:'Songs',path:folder,is_dir:true}]:[{name:'Track.mp3',path:album+'/Track.mp3',kind:'audio'}]}});return;}await route.fulfill({json:u.pathname==='/api/session'?{token:'fixture'}:u.pathname==='/api/state'?state:{ok:true}});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();await page.getByRole('button',{name:'Songs',exact:false}).tap();if(direction==='back'){await expect(page.getByRole('button',{name:'Track.mp3',exact:false})).toBeVisible();await page.getByRole('button',{name:lang==='ro'?'Dosarul anterior':'Up one level',exact:true}).tap();}
 await expect(page.locator('.media-items .empty-state')).toBeVisible();const failedTarget=direction==='folder'?folder:library,acceptedPath=direction==='folder'?library:folder;await expect(page.locator('.library-path')).toContainText(acceptedPath);expect(requested.at(-1)).toBe(failedTarget);const before=requested.length;if(theme==='night'&&retry==='inline')await page.screenshot({path:info.outputPath(`${direction}-error.png`)});
 await (retry==='inline'?page.locator('.media-items .empty-state'):page.locator('.error-strip')).getByRole('button',{name:lang==='ro'?'Încearcă din nou':'Try again',exact:true}).tap();await expect(page.locator('.media-items .empty-state')).toHaveCount(0);expect(requested.length).toBe(before+1);expect(requested.at(-1)).toBe(failedTarget);await expect(page.locator('.library-path')).toContainText(failedTarget);await expect(page.getByRole('button',{name:direction==='folder'?'Track.mp3':'Songs',exact:false})).toBeVisible();await expect(page.locator('.error-strip')).toHaveCount(0);if(theme==='night'&&retry==='inline')await page.screenshot({path:info.outputPath(`${direction}-recovered.png`)});
 });

for(const stale of ['success','failure'])test(`Media latest root response wins over delayed folder ${stale}`,async({page},info)=>{
 const lang=info.project.name.endsWith('ro')?'ro':'en';let release!:()=>void,completed!:()=>void;const gate=new Promise<void>(r=>release=r),done=new Promise<void>(r=>completed=r);let roots=0,folderPending=false;const state={preferences:{language:lang,theme:'night',setupComplete:true,screensaverMinutes:0},network:{},bluetooth:{devices:[],prompts:[]},audio:{},player:{},weather:{}};
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/api/media'){const target=u.searchParams.get('path')||'';if(target==='/library/Songs'){folderPending=true;await gate;try{await route.fulfill(stale==='success'?{json:{path:target,parent:'/library',items:[{name:'Late track.mp3',path:target+'/Late.mp3',kind:'audio'}]}}:{status:503,json:{error:'media_unavailable'}});}finally{completed();}return;}roots++;await route.fulfill({json:{path:'/library',parent:'',items:roots===1?[{name:'Songs',path:'/library/Songs',is_dir:true}]:[{name:'Root track.mp3',path:'/library/Root.mp3',kind:'audio'}]}});return;}await route.fulfill({json:u.pathname==='/api/session'?{token:'fixture'}:u.pathname==='/api/state'?state:{ok:true}});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();await page.getByRole('button',{name:'Songs',exact:false}).tap();await expect.poll(()=>folderPending).toBe(true);await expect(page.locator('.library-path')).toContainText('/library');await page.locator('.crumb-actions button').first().tap();await expect(page.getByRole('button',{name:'Root track.mp3',exact:false})).toBeVisible();release();await done;await expect(page.getByRole('button',{name:'Root track.mp3',exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Late track.mp3',exact:false})).toHaveCount(0);await expect(page.locator('.error-strip')).toHaveCount(0);await expect(page.locator('.library-path')).toContainText('/library');
});
