import {test,expect} from '@playwright/test';

for(const theme of ['ink','night'])test(`transport retry replaces missing selection ${theme}`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro'),plays:any[]=[],commands:any[]=[];
 const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,screensaverMinutes:0,nightEnabled:false},audio:{ready:true,volume:30},network:{},bluetooth:{devices:[],prompts:[]},player:{kind:'audio',state:'playing',url:'/Music/A.wav',title:'A.wav',canNext:true,canPrevious:true,position:1,duration:20},weather:{}};
 await page.route('**/api/**',async route=>{const endpoint=new URL(route.request().url()).pathname;let json:any={ok:true};if(endpoint==='/api/session')json={token:'fixture'};else if(endpoint==='/api/state')json=state;else if(endpoint==='/api/media')json={path:'',items:[{name:'B.wav',path:'/Music/B.wav',kind:'audio'}]};else if(endpoint==='/api/play'){plays.push(route.request().postDataJSON());return route.fulfill({status:409,json:{error:'media_not_found'}});}else if(endpoint==='/api/player'){commands.push(route.request().postDataJSON());if(commands.length===1)return route.fulfill({status:409,json:{error:'media_not_found'}});}await route.fulfill({json});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();await page.locator('.media-item').tap();const error=page.locator('.error-strip');await expect(error.locator('.media-error-filename')).toHaveText('B.wav');
 await page.getByRole('button',{name:ro?'Următor':'Next',exact:true}).tap();await expect.poll(()=>commands.length).toBe(1);await expect(error.locator('.media-error-filename')).toHaveCount(0);await error.getByRole('button',{name:ro?'Încearcă din nou':'Try again',exact:true}).tap();await expect.poll(()=>commands.length).toBe(2);expect(commands).toEqual([{action:'next'},{action:'next'}]);expect(plays).toEqual([{source:'local',path:'/Music/B.wav',title:'B.wav'}]);await expect(error).toHaveCount(0);
});

for(const theme of ['ink','night'])for(const long of [false,true])test(`missing file identifies owned target ${theme} long=${long}`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro'),filename=long?'Înregistrare cu nume foarte lung '.repeat(8)+'final.wav':'test.wav',target='/PRIVATE_DO_NOT_DISPLAY/album/'+filename,attempts:any[]=[];
 const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,screensaverMinutes:0,nightEnabled:false},audio:{ready:true,volume:30},network:{},bluetooth:{devices:[],prompts:[]},player:{state:'idle'},weather:{}};
 await page.route('**/api/**',async route=>{const endpoint=new URL(route.request().url()).pathname;let json:any={ok:true};if(endpoint==='/api/session')json={token:'fixture'};else if(endpoint==='/api/state')json=state;else if(endpoint==='/api/media')json={path:'',items:[{name:filename,path:target,kind:'audio'}]};else if(endpoint==='/api/play'){const body=route.request().postDataJSON();attempts.push(body);if(attempts.length<3)return route.fulfill({status:409,json:{error:'media_not_found'}});state.player={kind:'audio',state:'playing',url:body.path,title:body.title,position:1,duration:20};}await route.fulfill({json});});
 await page.goto('/');await page.locator('.main-nav button').nth(2).tap();await page.locator('.media-item').tap();const error=page.locator('.error-strip'),name=error.locator('.media-error-filename');await expect(name).toHaveText(filename);await expect(error).not.toContainText('PRIVATE_DO_NOT_DISPLAY');await expect(error).toContainText(ro?'Fișierul sau dosarul media nu este disponibil.':'This media file or folder is unavailable.');
 const controls=error.getByRole('button');for(const control of await controls.all()){const box=(await control.boundingBox())!;expect(box.width).toBeGreaterThanOrEqual(48);expect(box.height).toBeGreaterThanOrEqual(48);expect(box.x+box.width).toBeLessThanOrEqual(800);expect(box.y+box.height).toBeLessThanOrEqual(480);}
 await page.screenshot({path:info.outputPath('missing-target.png')});await error.getByRole('button',{name:ro?'Încearcă din nou':'Try again',exact:true}).tap();await expect.poll(()=>attempts.length).toBe(2);expect(attempts[1]).toEqual(attempts[0]);await expect(name).toHaveText(filename);await error.getByRole('button',{name:ro?'Încearcă din nou':'Try again',exact:true}).tap();await expect(error).toHaveCount(0);expect(attempts[2]).toEqual(attempts[0]);
 // A fresh failure must disappear on navigation, including its target identity.
 attempts.length=0;await page.locator('.media-item').tap();await expect(name).toHaveText(filename);await page.locator('.main-nav button').first().tap();await expect(error).toHaveCount(0);await page.locator('.main-nav button').nth(2).tap();await expect(name).toHaveCount(0);
});
