import {test,expect} from '@playwright/test';
for(const theme of ['ink','night']){
 test(`Recovery ${theme}: Bluetooth closed pending and error cannot idle, explicit dismissal restores ambient`,async({page},info)=>{
 const lang=info.project.name.endsWith('ro')?'ro':'en';let release!:()=>void;const gate=new Promise<void>(r=>release=r);let writes=0;
 const state={preferences:{language:lang,theme,setupComplete:true,nightEnabled:false,screensaverMinutes:1},network:{},bluetooth:{available:true,powered:true,devices:[],prompts:[]},audio:{},player:{},weather:{}};
 await page.route('**/api/**',async r=>{const p=new URL(r.request().url()).pathname;if(p==='/api/bluetooth/scan'){writes++;await gate;await r.fulfill({status:503,json:{error:'bluetooth_unavailable'}});return;}await r.fulfill({json:p==='/api/session'?{token:'fixture'}:p==='/api/state'?state:{ok:true}});});
 await page.clock.install();await page.goto('/');await page.locator('.rail-bottom button').nth(1).tap();const dialog=page.getByRole('dialog',{name:'Bluetooth',exact:true});await dialog.getByRole('button',{name:lang==='ro'?'Scanează':'Scan nearby',exact:true}).tap();await expect(dialog.getByRole('status')).toBeVisible();await dialog.getByRole('button',{name:lang==='ro'?'Închide':'Close',exact:true}).tap();const banner=page.locator('[data-recovery=bluetooth]');await expect(banner).toBeVisible();await expect(banner.getByRole('button',{name:lang==='ro'?'Închide':'Close',exact:true})).toHaveCount(0);
 await page.clock.runFor(65000);await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');await expect(page.locator('.pysh-screensaver')).toHaveCount(0);expect(writes).toBe(1);await page.locator('.main-nav button').nth(1).tap();await page.clock.runFor(65000);await expect(page.locator('.pysh-screensaver')).toHaveCount(0);await page.locator('.main-nav button').first().tap();release();await expect(banner).toHaveAttribute('role','alert');await page.screenshot({path:info.outputPath(`recovery-${theme}-error.png`)});const targets=await banner.getByRole('button').evaluateAll(els=>els.map(e=>e.getBoundingClientRect().height));expect(targets.every(height=>height>=48)).toBe(true);await page.clock.runFor(65000);await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');expect(writes).toBe(1);await banner.getByRole('button',{name:lang==='ro'?'Închide':'Close',exact:true}).tap();await expect(banner).toHaveCount(0);await page.clock.runFor(31000);await expect(page.locator('.app')).toHaveAttribute('data-home-phase','ambient');
 });
 test(`Recovery ${theme}: geocode remains visible after leaving Weather and error dismissal restores idle`,async({page},info)=>{
 const lang=info.project.name.endsWith('ro')?'ro':'en';let release!:()=>void;const gate=new Promise<void>(r=>release=r);let reads=0;
 const state={preferences:{language:lang,theme,setupComplete:true,nightEnabled:false,screensaverMinutes:1,location:{name:'Old place',latitude:1,longitude:2}},network:{},bluetooth:{devices:[],prompts:[]},audio:{},player:{},weather:{}};
 await page.route('**/api/**',async r=>{const p=new URL(r.request().url()).pathname;if(p==='/api/geocode'){reads++;await gate;await r.fulfill({status:503,json:{error:'geocode_unavailable'}});return;}await r.fulfill({json:p==='/api/session'?{token:'fixture'}:p==='/api/state'?state:{ok:true}});});
 await page.clock.install();await page.goto('/');await page.locator('.main-nav button').nth(3).tap();await page.locator('.settings-tabs button').filter({hasText:lang==='ro'?'Vreme':'Weather'}).tap();await page.getByRole('button',{name:'Old place',exact:true}).tap();await page.locator('.keyboard-card').getByRole('button',{name:lang==='ro'?'Aplică':'Apply',exact:true}).tap();await expect.poll(()=>reads).toBe(1);await page.locator('.main-nav button').first().tap();const banner=page.locator('[data-recovery=location]');await expect(banner).toBeVisible();await page.clock.runFor(65000);await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');release();await expect(banner).toHaveAttribute('role','alert');await page.clock.runFor(65000);await expect(page.locator('.app')).toHaveAttribute('data-home-phase','interactive');expect(reads).toBe(1);await banner.getByRole('button',{name:lang==='ro'?'Vreme':'Weather',exact:true}).tap();await page.getByRole('button',{name:'Old place',exact:true}).tap();await expect(page.locator('.keyboard-card')).toBeVisible();await page.clock.runFor(65000);await expect(page.locator('.pysh-screensaver')).toHaveCount(0);expect(await page.locator('.keyboard-card').evaluate(el=>{const b=el.getBoundingClientRect();return el.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2));})).toBe(true);await page.locator('.keyboard-card').getByRole('button',{name:lang==='ro'?'Închide':'Close',exact:true}).tap();await expect(page.locator('.settings-panel').getByRole('alert')).toBeVisible();await page.locator('.main-nav button').first().tap();await banner.getByRole('button',{name:lang==='ro'?'Închide':'Close',exact:true}).tap();await page.clock.runFor(31000);await expect(page.locator('.app')).toHaveAttribute('data-home-phase','ambient');
 });
 test(`Recovery ${theme}: pending location save and failure block non-Home screensaver with recoverable results`,async({page},info)=>{
 const lang=info.project.name.endsWith('ro')?'ro':'en';let release!:()=>void;const gate=new Promise<void>(r=>release=r);let writes=0;
 const state={preferences:{language:lang,theme,setupComplete:true,nightEnabled:false,screensaverMinutes:1,location:{name:'Old place',latitude:1,longitude:2}},network:{},bluetooth:{devices:[],prompts:[]},audio:{},player:{},weather:{}};
 await page.route('**/api/**',async r=>{const p=new URL(r.request().url()).pathname;if(p==='/api/preferences'){writes++;if(writes===1){await gate;await r.fulfill({status:500,json:{error:'preferences_unavailable'}});return;}Object.assign(state.preferences,r.request().postDataJSON());await r.fulfill({json:state.preferences});return;}await r.fulfill({json:p==='/api/session'?{token:'fixture'}:p==='/api/state'?state:p==='/api/geocode'?{results:[{name:'Sector 5',latitude:44.4,longitude:26.07}]}:{ok:true}});});
 await page.clock.install();await page.goto('/');await page.locator('.main-nav button').nth(3).tap();await page.locator('.settings-tabs button').filter({hasText:lang==='ro'?'Vreme':'Weather'}).tap();await page.getByRole('button',{name:'Old place',exact:true}).tap();await page.locator('.keyboard-card').getByRole('button',{name:lang==='ro'?'Aplică':'Apply',exact:true}).tap();await page.locator('.geo-item').first().tap();await expect.poll(()=>writes).toBe(1);await page.locator('.main-nav button').nth(1).tap();const banner=page.locator('[data-recovery=location]');await expect(banner).toBeVisible();await page.clock.runFor(65000);await expect(page.locator('.pysh-screensaver')).toHaveCount(0);release();await expect(banner).toHaveAttribute('role','alert');await page.clock.runFor(65000);await expect(page.locator('.pysh-screensaver')).toHaveCount(0);expect(writes).toBe(1);await banner.getByRole('button',{name:lang==='ro'?'Vreme':'Weather',exact:true}).tap();await expect(page.locator('.geo-item')).toHaveCount(1);await page.locator('.settings-panel').getByRole('alert').getByRole('button').tap();await expect(page.locator('.geo-item')).toHaveCount(0);expect(writes).toBe(2);await page.locator('.main-nav button').nth(1).tap();await page.clock.runFor(61000);await expect(page.locator('.pysh-screensaver')).toBeVisible();
 });
}
