import {expect,test} from '@playwright/test';
import {settingsFixture,retainsSettingsAndRadio} from './settings-fixture';
for(const base of ['ink','night'] as const){
 test(`Solar ${base}: real Settings choice crosses sunset sunrise and preserves selected base`,async({page},info)=>{
  const language=info.project.name.endsWith('ro')?'ro':'en',f=await settingsFixture(page,language,base,'2026-10-03T15:49:58Z');const night=page.getByRole('button',{name:language==='ro'?'Mod de noapte':'Night mode',exact:true});await night.scrollIntoViewIfNeeded();await night.tap();await page.getByRole('dialog').getByRole('radio',{name:language==='ro'?'Apus / răsărit':'Sunset / sunrise',exact:true}).tap();expect(f.writes).toEqual([{nightEnabled:true,nightMode:'solar'}]);await expect(page.locator('.app')).toHaveAttribute('data-theme','ink');await page.clock.runFor(1000);await expect(page.locator('.app')).toHaveAttribute('data-theme','ink');await page.clock.runFor(1000);await expect(page.locator('.app')).toHaveAttribute('data-theme','night');await retainsSettingsAndRadio(page,language);
  await page.clock.setSystemTime(new Date('2026-10-03T04:14:58Z'));await page.clock.runFor(1000);await expect(page.locator('.app')).toHaveAttribute('data-theme','night');await page.clock.runFor(1000);await expect(page.locator('.app')).toHaveAttribute('data-theme','ink');expect(f.state.preferences.theme).toBe(base);expect(f.other).toEqual([]);await page.reload();await expect(page.locator('.app')).toHaveAttribute('data-theme','ink');expect(f.state.preferences.nightEnabled).toBe(true);
 });
 test(`Solar ${base}: midnight rejects previous-day times, receives new day, then honors manual override`,async({page},info)=>{
  const language=info.project.name.endsWith('ro')?'ro':'en',f=await settingsFixture(page,language,base,'2026-10-03T20:59:58Z');const night=page.getByRole('button',{name:language==='ro'?'Mod de noapte':'Night mode',exact:true});await night.scrollIntoViewIfNeeded();await night.tap();await page.getByRole('dialog').getByRole('radio',{name:language==='ro'?'Apus / răsărit':'Sunset / sunrise',exact:true}).tap();await expect(page.locator('.app')).toHaveAttribute('data-theme','night');await page.clock.runFor(2000);await expect(page.locator('.date-label')).toContainText(language==='ro'?'4 octombrie':'4 October');await expect(page.locator('.app')).toHaveAttribute('data-theme',base);
  f.state.weather.daily.push({date:'2026-10-04',sunrise_epoch:Date.parse('2026-10-04T04:16:00Z')/1000,sunset_epoch:Date.parse('2026-10-04T15:48:00Z')/1000});await page.clock.runFor(2600);await expect(page.locator('.app')).toHaveAttribute('data-theme','night');f.state.weather.daily=[{date:'2026-10-04'}];await page.clock.runFor(2600);await expect(page.locator('.app')).toHaveAttribute('data-theme',base);await expect(page.locator('.setting-help').filter({hasText:language==='ro'?'Fără ore solare':'Without today’s solar times'})).toBeVisible();
  const manual=base==='ink'?page.locator('.theme-chip.ink-chip'):page.locator('.theme-chip.night-chip');await manual.scrollIntoViewIfNeeded();await manual.tap();expect(f.state.preferences.nightEnabled).toBe(false);f.state.weather.daily=[{date:'2026-10-04',sunrise_epoch:Date.parse('2026-10-04T04:16:00Z')/1000,sunset_epoch:Date.parse('2026-10-04T15:48:00Z')/1000}];await page.clock.runFor(2600);await expect(page.locator('.app')).toHaveAttribute('data-theme',base);await retainsSettingsAndRadio(page,language);expect(f.other).toEqual([]);await page.reload();await expect(page.locator('.app')).toHaveAttribute('data-theme',base);
 });
}
