import {expect,test} from '@playwright/test';
import {settingsFixture,retainsSettingsAndRadio} from './settings-fixture';
for(const initialTheme of ['ink','night'] as const){
 test(`Settings ${initialTheme}: actual language and theme changes preserve page playback and reload`,async({page},info)=>{
  const initial=info.project.name.endsWith('ro')?'ro':'en',f=await settingsFixture(page,initial,initialTheme);const sequence=initial==='en'?['ro','en'] as const:['en','ro'] as const;
  for(const language of sequence){await page.getByRole('button',{name:language==='ro'?'Română':'English',exact:true}).tap();await expect(page.locator('html')).toHaveAttribute('lang',language);await retainsSettingsAndRadio(page,language);await expect(page.locator('.top-clock')).toHaveText('15:04');await expect(page.locator('.date-label')).toContainText(language==='ro'?'sâmbătă':'Saturday');await expect(page.locator('.date-label')).toContainText(language==='ro'?'octombrie':'October');expect(f.state.preferences.language).toBe(language);}
  const opposite=initialTheme==='ink'?'night':'ink';for(const theme of [opposite,initialTheme]){await page.locator(`.theme-chip.${theme}-chip`).tap();await expect(page.locator('.app')).toHaveAttribute('data-theme',theme);await retainsSettingsAndRadio(page,initial);expect(f.state.preferences.nightEnabled).toBe(false);}
  expect(f.writes).toEqual([{language:sequence[0]},{language:sequence[1]},{theme:opposite,nightEnabled:false},{theme:initialTheme,nightEnabled:false}]);expect(f.other).toEqual([]);await page.reload();await expect(page.locator('html')).toHaveAttribute('lang',initial);await expect(page.locator('.app')).toHaveAttribute('data-theme',initialTheme);await page.locator('.main-nav button').nth(1).tap();await expect(page.locator('.radio-station-name')).toHaveText('Radio retained');
 });
 for(const key of ['language','theme'] as const)test(`Settings ${initialTheme}: rejected ${key} save preserves actual choice navigation and playback`,async({page},info)=>{
  const initial=info.project.name.endsWith('ro')?'ro':'en',f=await settingsFixture(page,initial,initialTheme);f.failKeys.add(key);
  if(key==='language')await page.getByRole('button',{name:initial==='en'?'Română':'English',exact:true}).tap();else await page.locator(`.theme-chip.${initialTheme==='ink'?'night':'ink'}-chip`).tap();await expect(page.locator('.error-strip')).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang',initial);await expect(page.locator('.app')).toHaveAttribute('data-theme',initialTheme);await retainsSettingsAndRadio(page,initial);await expect(page.getByRole('button',{name:initial==='ro'?'Română':'English',exact:true})).toHaveClass(/selected/);await expect(page.locator(`.theme-chip.${initialTheme}-chip`)).toHaveClass(/selected/);expect(f.other).toEqual([]);await page.reload();await expect(page.locator('html')).toHaveAttribute('lang',initial);await expect(page.locator('.app')).toHaveAttribute('data-theme',initialTheme);
 });
}
