import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';
for(const theme of ['ink','night'])test(`weather attribution stays informational without external navigation ${theme}`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro');const documents:string[]=[],popups:string[]=[];
 const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,nightEnabled:false,screensaverMinutes:0,navigationCollapsed:false,navigationAutoHide:false,visualizerStyle:'wave',visualizerSize:'large',homeCards:['weather','forecast','playback'],homePositions:{},location:{name:'București, Sectorul 5',latitude:44.4,longitude:26.07}},network:{state:'connected'},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'playing',kind:'radio',station_name:'Station',url:'https://example.org/stream'},weather:{current:{temperature_c:13,weather_code:0,is_day:0},daily:Array.from({length:5},(_,i)=>({date:`2026-10-0${i+4}`,weather_code:0,max_c:22,min_c:11})),stale:false,attribution:'Weather data by Open-Meteo, CC BY 4.0'}};

 page.on('popup',popup=>popups.push(popup.url()));
 await page.route('**/api/**',async route=>{const p=new URL(route.request().url()).pathname;let json:any={ok:true};if(p==='/api/session')json={token:'fixture'};else if(p==='/api/state')json=state;else if(p==='/api/preferences'){Object.assign(state.preferences,route.request().postDataJSON());json=state.preferences;}else if(p==='/api/documentation'){documents.push(route.request().postDataJSON().provider);json={opened:true,preparing:false};}else if(p==='/api/audio/visualization')json={available:true,status:'ready',waveform:Array(64).fill(.2),bars:Array(16).fill(.3),rms:.2,peak:.3,silent:false};await route.fulfill({json});});
 await page.clock.install();await page.goto('/');await expect(page.locator('.ambient-weather')).toBeVisible();await page.clock.runFor(400);
 const check=async()=>{await expect(page.locator('.ambient-home .weather-source')).toHaveCount(0);await expect(page.locator('.ambient-home a[href*="open-meteo"],.ambient-home a[href*="creativecommons"]')).toHaveCount(0);expect(documents).toEqual([]);expect(popups).toEqual([]);};
 await check();await page.screenshot({path:info.outputPath(`weather-no-link-expanded-${theme}.png`)});
 await page.clock.runFor(16000);await check();await page.screenshot({path:info.outputPath(`weather-no-link-compact-${theme}.png`)});
 await page.locator('.weather-heading').tap();await expect(page.locator('.weather-heading')).toHaveAttribute('aria-expanded','true');await check();
 await page.locator('.main-nav button').nth(3).tap();await page.locator('.settings-tabs button').filter({hasText:ro?'Vreme':'Weather'}).tap();
 const credit=page.locator('.settings-panel .weather-source');await expect(credit).toContainText('Open-Meteo');await expect(credit).toContainText('CC BY 4.0');await expect(credit.locator('a,button,[role=button]')).toHaveCount(0);await expect(page.locator('.weather-provenance')).toContainText(ro?'rotunjește':'rounds');await credit.tap();expect(documents).toEqual([]);expect(popups).toEqual([]);
 await page.screenshot({path:info.outputPath(`weather-informational-credit-${theme}.png`)});
 await page.locator('.settings-tabs button').filter({hasText:ro?'Acasă':'Home'}).tap();await page.getByRole('button',{name:ro?'Aranjează Acasă':'Arrange Home',exact:true}).tap();await expect(page.locator('.ambient-home')).toHaveAttribute('data-layout-editing','true');await check();await page.getByRole('button',{name:ro?'Anulează':'Cancel',exact:true}).tap();
 state.weather.stale=true;await page.reload();await expect(page.locator('.ambient-weather')).toBeVisible();await check();
});
for(const language of ['en','ro'])test(`documentation persistent return and outward link ${language}`,async({page},info)=>{
 await page.route('https://open-meteo.com/**',route=>route.fulfill({contentType:'text/html',body:'<h1>Provider fixture</h1><a id="outside" href="https://evil.example/" target="_blank">Outside</a><a id="licence" href="https://creativecommons.org/licenses/by/4.0/">Licence</a>'}));await page.goto('https://open-meteo.com/');await page.evaluate(language=>{(window as any).actions=[];(window as any).chrome={runtime:{sendMessage:(message:any,callback?:Function)=>{(window as any).actions.push(message.action);callback?.({language});}}};},language);await page.addScriptTag({content:readFileSync('app/browser-extension/documentation.js','utf8')});
 await page.waitForTimeout(5000);const host=page.locator('pi-hub-documentation-return');await expect(host).toBeVisible();const box=(await host.boundingBox())!;expect(box.width).toBeGreaterThanOrEqual(160);expect(box.height).toBeGreaterThanOrEqual(48);await page.locator('#outside').click();expect(page.url()).toBe('https://open-meteo.com/');await expect(host).toBeVisible();await page.mouse.click(box.x+60,box.y+24);expect(await page.evaluate(()=>(window as any).actions.at(-1))).toBe('return');await page.screenshot({path:info.outputPath(`documentation-return-${language}.png`)});
});
