import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';
for(const theme of ['ink','night'])test(`weather source placement, editor and failure ${theme}`,async({page},info)=>{
 const ro=info.project.name.endsWith('ro');let fail=false,hold=false;let release:undefined|(()=>void);const documents:string[]=[],other:string[]=[];
 const state:any={preferences:{language:ro?'ro':'en',theme,setupComplete:true,nightEnabled:false,screensaverMinutes:0,navigationCollapsed:false,navigationAutoHide:false,visualizerStyle:'wave',visualizerSize:'large',homeCards:['weather','forecast','playback'],homePositions:{},location:{name:'București, Sectorul 5',latitude:44.4,longitude:26.07}},network:{state:'connected'},bluetooth:{devices:[],prompts:[]},audio:{ready:true,volume:30,mute:false},player:{state:'playing',kind:'radio',station_name:'Station',url:'https://example.org/stream'},weather:{current:{temperature_c:13,weather_code:0,is_day:0},daily:Array.from({length:5},(_,i)=>({date:`2026-10-0${i+4}`,weather_code:0,max_c:22,min_c:11})),stale:false,attribution:'Weather data by Open-Meteo, CC BY 4.0'}};
 await page.route('**/api/**',async route=>{const p=new URL(route.request().url()).pathname;let json:any={ok:true};if(p==='/api/session')json={token:'fixture'};else if(p==='/api/state')json=state;else if(p==='/api/preferences'){Object.assign(state.preferences,route.request().postDataJSON());json=state.preferences;}else if(p==='/api/documentation'){documents.push(route.request().postDataJSON().provider);if(hold)await new Promise<void>(resolve=>{release=resolve;});if(fail)return route.fulfill({status:409,json:{error:'browser_unavailable'}});json={opened:true,preparing:false};}else if(p==='/api/audio/visualization')json={available:true,status:'ready',waveform:Array(64).fill(.2),bars:Array(16).fill(.3),rms:.2,peak:.3,silent:false};else if(route.request().method()==='POST')other.push(p);await route.fulfill({json});});
 await page.clock.install();await page.goto('/');await expect(page.locator('.ambient-weather')).toBeVisible();await page.clock.runFor(400);
 const source=page.locator('.ambient-weather .weather-source a');await expect(source).toHaveAttribute('href','https://open-meteo.com/');await source.tap();expect(documents).toEqual(['open-meteo']);expect(other).toEqual([]);
 hold=true;await source.tap();await expect(source).toHaveAttribute('aria-disabled','true');await source.dispatchEvent('click');await source.dispatchEvent('click');expect(documents).toEqual(['open-meteo','open-meteo']);release!();hold=false;await expect(source).not.toHaveAttribute('aria-disabled','true');
 const check=async()=>{for(const selector of ['.ambient-weather','.ambient-forecast']){const data=await page.locator(selector).evaluate(el=>{const card=el.getBoundingClientRect(),source=el.querySelector('.weather-source a')!.getBoundingClientRect();return {card:{x:card.x,y:card.y,right:card.right,bottom:card.bottom},source:{x:source.x,y:source.y,right:source.right,bottom:source.bottom,width:source.width,height:source.height},overflow:el.scrollHeight-el.clientHeight};});expect(data.source.width).toBeGreaterThanOrEqual(48);expect(data.source.height).toBeGreaterThanOrEqual(48);expect(data.source.right).toBeLessThanOrEqual(data.card.right);expect(data.source.bottom).toBeLessThanOrEqual(data.card.bottom);expect(data.overflow).toBeLessThanOrEqual(1);}};await check();await page.screenshot({path:info.outputPath(`attribution-expanded-${theme}.png`)});
 await page.clock.runFor(16000);await check();await page.screenshot({path:info.outputPath(`attribution-compact-${theme}.png`)});
 state.preferences.homeCards=['weather','playback'];state.weather.stale=true;await page.reload();await expect(source).toBeVisible();await source.tap();
 const settings=async()=>{await page.locator('.main-nav button').nth(3).tap();};await settings();await page.locator('.settings-tabs button').filter({hasText:ro?'Vreme':'Weather'}).tap();const licence=page.locator('.settings-panel a[href="https://creativecommons.org/licenses/by/4.0/"]');await expect(licence).toBeVisible();await expect(page.locator('.weather-provenance')).toContainText(ro?'rotunjește':'rounds');await licence.tap();expect(documents.at(-1)).toBe('cc-by');await page.screenshot({path:info.outputPath(`attribution-settings-${theme}.png`)});
 await page.locator('.settings-tabs button').filter({hasText:ro?'Acasă':'Home'}).tap();await page.getByRole('button',{name:ro?'Aranjează Acasă':'Arrange Home',exact:true}).tap();await expect(source).toBeVisible();await source.tap();await expect(page.locator('.ambient-home')).toHaveAttribute('data-layout-editing','true');await page.getByRole('button',{name:ro?'Anulează':'Cancel',exact:true}).tap();
 fail=true;await source.tap();await expect(page.locator('.error-strip')).toBeVisible();fail=false;await source.tap();await expect(page.locator('.error-strip')).toHaveCount(0);expect(other).toEqual([]);
});
for(const language of ['en','ro'])test(`documentation persistent return and outward link ${language}`,async({page},info)=>{
 await page.route('https://open-meteo.com/**',route=>route.fulfill({contentType:'text/html',body:'<h1>Provider fixture</h1><a id="outside" href="https://evil.example/" target="_blank">Outside</a><a id="licence" href="https://creativecommons.org/licenses/by/4.0/">Licence</a>'}));await page.goto('https://open-meteo.com/');await page.evaluate(language=>{(window as any).actions=[];(window as any).chrome={runtime:{sendMessage:(message:any,callback?:Function)=>{(window as any).actions.push(message.action);callback?.({language});}}};},language);await page.addScriptTag({content:readFileSync('app/browser-extension/documentation.js','utf8')});
 await page.waitForTimeout(5000);const host=page.locator('pi-hub-documentation-return');await expect(host).toBeVisible();const box=(await host.boundingBox())!;expect(box.width).toBeGreaterThanOrEqual(160);expect(box.height).toBeGreaterThanOrEqual(48);await page.locator('#outside').click();expect(page.url()).toBe('https://open-meteo.com/');await expect(host).toBeVisible();await page.mouse.click(box.x+60,box.y+24);expect(await page.evaluate(()=>(window as any).actions.at(-1))).toBe('return');await page.screenshot({path:info.outputPath(`documentation-return-${language}.png`)});
});
