"""Guarded runtime-only PySH OS updates. No package, account or OS configuration edits."""
import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import socket
import stat
import subprocess
import tarfile
import time
import urllib.request
import uuid


class Refused(RuntimeError):
    pass


PROTECTED = {'etc/xdg/labwc/rc.xml', 'etc/chromium/native-messaging-hosts/org.pysh.keyboard.json',
             'etc/systemd/user/pysh.service', 'home/pysh/.local/share/pi-smart-hub/preferences.json',
             'home/pysh/.local/share/pi-smart-hub/preferences.backup.json'}


def require(condition, message):
    if not condition:
        raise Refused(message)


def digest(path):
    with path.open('rb') as stream:
        h = hashlib.file_digest(stream, 'sha256')
    return h.hexdigest()


def allowed(name):
    p = PurePosixPath(name)
    return (str(p) == name and not p.is_absolute() and '..' not in p.parts
            and '\\' not in name and '__pycache__' not in p.parts and not name.endswith('.pyc')
            and (name.startswith(('services/backend/', 'app/browser-extension/', 'dist/'))
                 or name in {'requirements.lock', 'scripts/run-hub.py', 'scripts/install-session.sh',
                             'scripts/activate-release.sh', 'scripts/rollback.sh',
                             'scripts/probe-application.py', 'scripts/service-keyboard-host.py'}))


def identity(files):
    return hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest()[:12]


def transaction(value):
    require(isinstance(value, dict) and set(value) == {'id', 'old', 'new', 'protected', 'device', 'previous'}, 'Invalid transaction')
    require(re.fullmatch('[0-9a-f]{32}', value['id']) and re.fullmatch('[0-9a-f]{64}', value['device']), 'Invalid transaction identity')
    for key in ['old', 'new']:
        m = value[key]
        require(isinstance(m, dict) and set(m) == {'build', 'source_commit', 'files'}, 'Invalid source identity')
        manifest({'build': m['build'], 'files': m['files'], 'sha256': '0' * 64})
        require(re.fullmatch('[0-9a-f]{40}', m['source_commit']), 'Invalid source commit')
    require(set(value['protected']) == PROTECTED and all(h is None or re.fullmatch('[0-9a-f]{64}', h)
            for h in value['protected'].values()), 'Invalid protected inventory')
    require(value['previous'] is None or isinstance(value['previous'], str), 'Invalid previous pointer')
    return value


def manifest(value):
    require(isinstance(value, dict) and set(value) == {'build', 'sha256', 'files'}, 'Invalid manifest fields')
    files = value['files']
    require(isinstance(files, dict) and 1 <= len(files) <= 5000, 'Invalid file inventory')
    require(all(allowed(n) and isinstance(h, str) and re.fullmatch('[0-9a-f]{64}', h)
                for n, h in files.items()), 'Unsafe manifest file')
    require(value['build'] == identity(files), 'Build identity mismatch')
    require(re.fullmatch('[0-9a-f]{64}', value['sha256']) is not None, 'Invalid archive hash')
    require({'requirements.lock', 'scripts/run-hub.py', 'dist/index.html'} <= files.keys(), 'Incomplete runtime')
    return value


def inventory(path):
    require(path.is_dir() and not path.is_symlink(), 'Runtime must be a real directory')
    files = {}
    for p in path.rglob('*'):
        require(not p.is_symlink(), 'Runtime symlink refused')
        if p.is_dir():
            continue
        name = p.relative_to(path).as_posix()
        # CPython caches are generated by the runtime, never executable release inputs.
        if '__pycache__' in p.parts and p.suffix == '.pyc':
            continue
        require(p.is_file() and allowed(name), 'Unknown runtime file: ' + name)
        files[name] = digest(p)
    return files


def verify(path, files):
    require(inventory(path) == files, 'Installed runtime differs from manifest')


def sync_directory(path):
    if os.name == 'posix':
        descriptor = os.open(path, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(descriptor)
        finally:
            os.close(descriptor)


def sync_runtime(path, files):
    if os.name == 'posix':
        for name in files:
            with (path / name).open('rb') as stream:
                os.fsync(stream.fileno())
        directories = [p for p in path.rglob('*') if p.is_dir()]
        for directory in sorted(directories, key=lambda p: len(p.parts), reverse=True):
            sync_directory(directory)
        sync_directory(path)
        sync_directory(path.parent)


def atomic_json(path, data):
    temporary = path.with_name('.metadata-' + uuid.uuid4().hex)
    with temporary.open('x', encoding='utf-8') as stream:
        json.dump(data, stream, indent=2)
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(temporary, path)
    sync_directory(path.parent)


def read_json(path):
    require(path.is_file() and not path.is_symlink() and path.stat().st_size <= 4_000_000, 'Invalid metadata file')
    return json.loads(path.read_text(encoding='utf-8'))


def host_id():
    p = Path('/etc/machine-id')
    return hashlib.sha256((p.read_bytes() if p.exists() else socket.gethostname().encode())).hexdigest()


def check_backup(path, expected):
    require(digest(path) == expected, 'Backup checksum mismatch')
    with tarfile.open(path, 'r:gz') as archive:
        record = archive.getmember('transaction.json')
        require(record.isfile() and record.size <= 4_000_000, 'Invalid backup transaction')
        t = transaction(json.load(archive.extractfile(record)))
        expected_files = {'runtime/' + n: h for n, h in t['old']['files'].items()}
        expected_files.update({'protected/' + n: h for n, h in t['protected'].items() if h is not None})
        seen = set()
        for member in archive:
            require(member.isfile() and member.name not in seen and
                    not PurePosixPath(member.name).is_absolute() and '..' not in PurePosixPath(member.name).parts,
                    'Unsafe backup member')
            seen.add(member.name)
            stream = archive.extractfile(member)
            h = hashlib.file_digest(stream, 'sha256').hexdigest()
            if member.name != 'transaction.json':
                require(expected_files.get(member.name) == h, 'Backup member hash mismatch')
        require(seen == set(expected_files) | {'transaction.json'}, 'Incomplete backup')
        return t


class Appliance:
    def __init__(self, base=Path('/'), runner=None):
        self.base = Path(base)
        self.root = self.base / 'opt/pysh'
        self.state = self.root / 'update'
        self.runner = runner or self.unit

    def guards(self):
        for path in [self.root, self.root / 'releases', self.state]:
            require(not path.is_symlink() and path.resolve().is_relative_to(self.base.resolve()), 'Unsafe appliance layout')
            if path.exists():
                require(path.is_dir(), 'Appliance layout is not a directory')
                if os.name == 'posix':
                    owner = 0 if self.base == Path('/') else os.geteuid()
                    require(path.stat().st_uid == owner, 'Appliance layout has foreign owner')
                    require(stat.S_IMODE(path.stat().st_mode) & (0o077 if path == self.state else 0o022) == 0,
                            'Insecure appliance state permissions' if path == self.state else 'Writable appliance layout')
            for parent in path.parents:
                if parent == self.base:
                    break
                require(not parent.is_symlink(), 'Appliance ancestor symlink')
        image = read_json(self.base / 'etc/pysh-build.json')
        require(re.fullmatch('[0-9a-f]{12}', image.get('runtime_build', '')) and
                re.fullmatch('[0-9a-f]{40}', image.get('source', '')), 'Missing PySH OS identity')
        return image

    def active(self):
        image = self.guards()
        current = self.root / 'current'
        if current.is_symlink():
            target = current.resolve(strict=True)
            require(target.parent == self.root / 'releases' and not target.is_symlink(), 'Foreign current target')
            metadata = read_json(self.root / 'runtime-source.json')
            files = inventory(target)
            require(metadata.get('build') == target.name == identity(files) and metadata.get('files') == files,
                    'Active runtime identity mismatch')
        else:
            target = current
            files = inventory(target)
            require(identity(files) == image['runtime_build'], 'Image runtime was modified')
            metadata = {'build': image['runtime_build'], 'source_commit': image['source'], 'files': files}
        require(re.fullmatch('[0-9a-f]{40}', metadata.get('source_commit', '')), 'Missing source commit')
        return target, metadata

    def prepare(self, archive, package, source, retained_target=False):
        require(re.fullmatch('[0-9a-f]{40}', source), 'Invalid source commit')
        old, oldmeta = self.active()
        require(not (self.state / 'transaction.json').exists(), 'Recover or finish pending transaction first')
        m = manifest(read_json(package))
        require(digest(archive) == m['sha256'] and m['build'] != oldmeta['build'], 'Invalid or unchanged archive')
        self.root.joinpath('releases').mkdir(exist_ok=True)
        self.state.mkdir(mode=0o700 if os.name == 'posix' else 0o777, exist_ok=True)
        target = self.root / 'releases' / m['build']
        require(not target.is_symlink(), 'Release symlink refused')
        require(retained_target or not target.exists(), 'Release already exists; never overwrite')
        with tarfile.open(archive, 'r:gz') as bundle:
            members = bundle.getmembers()
            require(len(members) == len(m['files']) and {x.name for x in members} == set(m['files']), 'Archive inventory mismatch')
            require(all(x.isfile() and x.size <= 64 * 1024 * 1024 and allowed(x.name) for x in members), 'Unsafe archive member')
            require(sum(x.size for x in members) < 512 * 1024 * 1024, 'Archive too large')
            if retained_target:
                verify(target, m['files'])
            else:
                target.mkdir(mode=0o755)
            for member in ([] if retained_target else members):
                output = target / member.name
                output.parent.mkdir(parents=True, exist_ok=True)
                with output.open('xb') as stream:
                    shutil.copyfileobj(bundle.extractfile(member), stream)
                output.chmod(0o755 if member.name == 'scripts/service-keyboard-host.py' else 0o644)
        verify(target, m['files'])
        require((target / 'requirements.lock').read_bytes() == (old / 'requirements.lock').read_bytes(),
                'Dependency changes require separate image/venv procedure')
        retained = self.root / 'releases' / oldmeta['build']
        if old == self.root / 'current':
            require(not retained.exists(), 'Conflicting initial image release')
            shutil.copytree(old, retained, ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
        verify(retained, oldmeta['files'])
        sync_runtime(target, m['files'])
        sync_runtime(retained, oldmeta['files'])
        previous = self.root / 'previous'
        if previous.exists() or previous.is_symlink():
            require(previous.is_symlink() and previous.resolve().parent == self.root / 'releases', 'Unsafe previous pointer')
        for name in PROTECTED:
            p = self.base / name
            while p != self.base:
                require(not p.is_symlink(), 'Protected state symlink')
                p = p.parent
        saved = {n: digest(self.base / n) if (self.base / n).is_file() else None for n in PROTECTED}
        token = uuid.uuid4().hex
        transaction = {'id': token, 'old': oldmeta, 'new': {'build': m['build'], 'source_commit': source, 'files': m['files']},
                       'protected': saved, 'device': host_id(), 'previous': str(previous.resolve()) if previous.exists() else None}
        backup = self.state / (token + '.backup.tar.gz')
        require(not backup.exists(), 'Backup already exists')
        transaction_file = self.state / 'transaction.json'
        atomic_json(transaction_file, transaction)
        descriptor = os.open(backup, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, 'O_NOFOLLOW', 0), 0o600)
        with os.fdopen(descriptor, 'wb') as stream:
            with tarfile.open(fileobj=stream, mode='w:gz') as bundle:
                bundle.add(transaction_file, arcname='transaction.json', recursive=False)
                for name in oldmeta['files']:
                    bundle.add(retained / name, arcname='runtime/' + name, recursive=False)
                for name, sha in saved.items():
                    if sha is not None:
                        require(not (self.base / name).is_symlink(), 'Protected config symlink')
                        bundle.add(self.base / name, arcname='protected/' + name, recursive=False)
            stream.flush()
            os.fsync(stream.fileno())
        sync_directory(self.state)
        checksum = digest(backup)
        check_backup(backup, checksum)
        return {'build': m['build'], 'backup': str(backup), 'backup_sha256': checksum, 'device': transaction['device']}

    def prepare_rollback(self):
        _, current = self.active()
        previous = self.root / 'previous'
        require(previous.is_symlink() and previous.resolve().parent == self.root / 'releases', 'Missing owned rollback pointer')
        records = [transaction(read_json(p)) for p in self.state.glob('*.activated.json')]
        matches = [r for r in records if r['new'] == current and r['old']['build'] == previous.resolve().name]
        require(matches, 'No exact recorded rollback source')
        record = matches[-1]
        old = record['old']
        require(previous.is_symlink() and previous.resolve() == self.root / 'releases' / old['build'], 'Unknown rollback target')
        verify(previous.resolve(), old['files'])
        token = uuid.uuid4().hex
        archive = self.state / (token + '.rollback.tar.gz')
        require(not archive.exists(), 'Rollback package already exists')
        with tarfile.open(archive, 'w:gz') as bundle:
            for name in old['files']:
                bundle.add(previous.resolve() / name, arcname=name, recursive=False)
        package = self.state / (token + '.rollback.manifest.json')
        atomic_json(package, {'build': old['build'], 'files': old['files'], 'sha256': digest(archive)})
        return self.prepare(archive, package, old['source_commit'], retained_target=True)

    def unit(self, action, target=None):
        import pwd
        uid = pwd.getpwnam('pysh').pw_uid
        command = ['runuser', '-u', 'pysh', '--', 'env', f'XDG_RUNTIME_DIR=/run/user/{uid}',
                   f'DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/{uid}/bus', 'systemctl', '--user']
        if action != 'ready':
            subprocess.run(command + [action, 'pysh.service'], check=True, timeout=30)
            return
        deadline = time.monotonic() + 30
        while time.monotonic() < deadline:
            try:
                pid = int(subprocess.check_output(command + ['show', 'pysh.service', '-p', 'MainPID', '--value'], text=True))
                state = json.load(urllib.request.urlopen('http://127.0.0.1:8765/api/state', timeout=2))
                if pid > 0 and Path('/proc', str(pid), 'cwd').resolve() == target and state.get('appliance') is True:
                    return
            except (OSError, ValueError):
                pass
            time.sleep(.25)
        raise Refused('Runtime readiness failed')

    def link(self, build, name='current'):
        require(re.fullmatch('[0-9a-f]{12}', build), 'Invalid release name')
        target = self.root / 'releases' / build
        require(target.is_dir() and not target.is_symlink(), 'Missing retained runtime')
        temporary = self.root / (name + '.next')
        if temporary.is_symlink():
            require(temporary.resolve().parent == self.root / 'releases', 'Foreign pointer temporary')
            temporary.unlink()
        require(not temporary.exists(), 'Unexpected pointer temporary')
        temporary.symlink_to(target, target_is_directory=True)
        os.replace(temporary, self.root / name)
        sync_directory(self.root)

    def protected(self, transaction):
        for name, sha in transaction['protected'].items():
            p = self.base / name
            require(not p.is_symlink() and (digest(p) if p.is_file() else None) == sha, 'Protected state changed: ' + name)

    def recover(self):
        self.guards()
        if not (self.state / 'transaction.json').exists():
            return {'recovered': self.active()[1]['build'], 'pending': False}
        t = transaction(read_json(self.state / 'transaction.json'))
        verify(self.root / 'releases' / t['old']['build'], t['old']['files'])
        self.runner('stop')
        current = self.root / 'current'
        if current.is_dir() and not current.is_symlink():
            verify(current, t['old']['files'])
            restored = current
        else:
            self.link(t['old']['build'])
            restored = self.root / 'releases' / t['old']['build']
        atomic_json(self.root / 'runtime-source.json', t['old'])
        if t['previous']:
            require(Path(t['previous']).parent == self.root / 'releases', 'Unsafe recorded previous')
            self.link(Path(t['previous']).name, 'previous')
        elif (self.root / 'previous').is_symlink():
            require((self.root / 'previous').resolve().parent == self.root / 'releases', 'Foreign previous pointer')
            (self.root / 'previous').unlink()
        self.runner('start')
        self.runner('ready', restored)
        self.protected(t)
        (self.state / 'transaction.json').rename(self.state / (t['id'] + '.recovered.json'))
        sync_directory(self.state)
        return {'recovered': t['old']['build']}

    def activate(self, receipt):
        self.active()
        t = transaction(read_json(self.state / 'transaction.json'))
        require(self.active()[1] == t['old'], 'Current release changed since prepare')
        r = read_json(receipt)
        backup = self.state / (t['id'] + '.backup.tar.gz')
        require(r == {'build': t['new']['build'], 'backup_sha256': digest(backup),
                      'device': t['device'], 'verified_on': r.get('verified_on')} and
                re.fullmatch('[0-9a-f]{64}', r.get('verified_on', '')) and r['verified_on'] != t['device'],
                'Separate-host verified backup receipt required')
        require(check_backup(backup, r['backup_sha256']) == t, 'Backup transaction mismatch')
        verify(self.root / 'releases' / t['new']['build'], t['new']['files'])
        self.protected(t)
        try:
            self.runner('stop')
            current = self.root / 'current'
            if not current.is_symlink():
                retained = self.root / ('image-current-' + t['old']['build'])
                require(not retained.exists(), 'Unexpected retained image directory')
                current.rename(retained)
                sync_directory(self.root)
            self.link(t['new']['build'])
            atomic_json(self.root / 'runtime-source.json', t['new'])
            self.runner('start')
            self.runner('ready', self.root / 'releases' / t['new']['build'])
            self.protected(t)
            verify(self.root / 'releases' / t['new']['build'], t['new']['files'])
            self.link(t['old']['build'], 'previous')
        except BaseException:
            self.recover()
            raise
        (self.state / 'transaction.json').rename(self.state / (t['id'] + '.activated.json'))
        sync_directory(self.state)
        return {'activated': t['new']['build'], 'previous': t['old']['build'], 'source_commit': t['new']['source_commit']}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest='command', required=True)
    p = commands.add_parser('prepare')
    p.add_argument('archive', type=Path)
    p.add_argument('manifest', type=Path)
    p.add_argument('--source', required=True)
    p = commands.add_parser('verify-backup')
    p.add_argument('backup', type=Path)
    p.add_argument('--sha256', required=True)
    p.add_argument('--receipt', type=Path, required=True)
    p = commands.add_parser('activate')
    p.add_argument('receipt', type=Path)
    commands.add_parser('recover')
    commands.add_parser('prepare-rollback')
    args = parser.parse_args()
    if args.command == 'verify-backup':
        t = check_backup(args.backup, args.sha256)
        require(host_id() != t['device'], 'Verify on a separate computer')
        require(not args.receipt.exists(), 'Receipt already exists')
        atomic_json(args.receipt, {'build': t['new']['build'], 'backup_sha256': args.sha256,
                                   'device': t['device'], 'verified_on': host_id()})
        result = {'verified': t['new']['build'], 'receipt': str(args.receipt)}
    else:
        require(os.name == 'posix' and os.geteuid() == 0, 'Appliance commands require Linux root')
        import fcntl
        with Path('/run/lock/pysh-release.lock').open('a') as lock:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            appliance = Appliance()
            result = (appliance.prepare(args.archive, args.manifest, args.source) if args.command == 'prepare'
                      else appliance.activate(args.receipt) if args.command == 'activate'
                      else appliance.prepare_rollback() if args.command == 'prepare-rollback' else appliance.recover())
    print(json.dumps(result))


if __name__ == '__main__':
    main()
