import {createPortal} from 'react-dom';
import { MarqueeText } from './MarqueeText';
import {useEffect,useState,useId,type ReactNode} from 'react';
import {StationArtwork} from './Radio';
import {TouchChoice} from './TouchChoice';
import {Meteors} from './Meteors';
import {useHomeLayout,type HomePositions,type HomeKey} from './HomeLayout';
import { WeatherIcon } from './WeatherIcon';
import {Moon} from './Moon';
import {AmbientEvents} from './AmbientEvents';
import { weatherCondition, weatherIsNight } from './weatherCondition';
type Props = {
 wakeEpoch?:number;time:string;date:string;language:'en'|'ro';timezone:string;greeting:string;
 weather:any;temperature:unknown;condition:string;location:string;stale:boolean;
 player:any;stationName:string;station?:any;trackTitle:string;audioReady:boolean;canPlay:boolean;pauses:boolean;
 homeCards:string[];visualizerSize:'compact'|'balanced'|'large';positions:HomePositions;layoutEditing:boolean;onSaveLayout:(positions:HomePositions)=>Promise<boolean>;onCancelLayout:()=>void;shortcuts:string[];t:(key:string)=>string;icon:(name:string,size?:number)=>ReactNode;
 onWeather:()=>void;onToggle:()=>void;onStop:()=>void;onNavigate:(page:'radio'|'media')=>void;visualizer?:ReactNode;
};
const degrees=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?`${Math.round(v)}°`:'—';
const measured=(v:unknown,u:string)=>typeof v==='number'&&Number.isFinite(v)?`${Math.round(v)} ${u}`:'—';
// Interaction renews only this card's timer; API/clock updates must not keep it open.
function useAmbientCard(editing:boolean,wakeEpoch:number){
 const [expanded,setExpanded]=useState(true),[activity,setActivity]=useState(0);
 useEffect(()=>{if(editing||wakeEpoch>0)setExpanded(false);},[editing,wakeEpoch]);
 useEffect(()=>{if(!expanded)return;const timer=window.setTimeout(()=>setExpanded(false),15000);return()=>window.clearTimeout(timer);},[expanded,activity]);
 return {expanded,toggle:()=>{setExpanded(v=>!v);setActivity(v=>v+1);},touch:()=>setActivity(v=>v+1)};
}
const cityWindows=[{x:25,y:53,w:32},{x:78,y:66,w:37},{x:153,y:46,w:63},{x:236,y:60,w:47},{x:310,y:67,w:49},{x:382,y:60,w:67},{x:468,y:69,w:63},{x:556,y:62,w:56},{x:636,y:72,w:58}].flatMap((b,building)=>Array.from({length:Math.floor(b.w/8)*Math.floor((116-b.y)/10)},(_,i)=>{const columns=Math.floor(b.w/8),col=i%columns,row=Math.floor(i/columns),seed=building*43+i*19;return seed%13<4?{x:b.x+4+col*8+(building%3),y:b.y+5+row*(9+building%2),width:building%3===0?1.8:1.2,height:2.2+(building%2)*.5,opacity:.16+(seed%7)*.055}:null;}).filter((w):w is NonNullable<typeof w>=>w!==null));
export function AmbientSky({code,isDay,stale,aircraft=true,lunarDust=false}:{code:unknown;isDay:unknown;stale:boolean;aircraft?:boolean;lunarDust?:boolean}){
 const skyId=useId().replace(/:/g,'');
 const category=weatherCondition(stale?null:code),known=!['missing','unknown'].includes(category)&&[true,false,0,1].includes(isDay as boolean|number),night=known&&weatherIsNight(isDay as boolean|number|null);
 const clear=category==='clear',rain=['rain','rain-showers','drizzle','freezing-rain','freezing-drizzle','thunder','thunder-hail'].includes(category),snow=['snow','snow-showers'].includes(category);
 return <div className={`ambient-sky ${known?(night?'sky-night':'sky-day'):'sky-neutral'} sky-${category}`} aria-hidden="true">
 {night&&['clear','mainly-clear','partly-cloudy'].includes(category)&&<svg className="ambient-stars" viewBox="0 0 694 422" preserveAspectRatio="none"><defs><linearGradient id={'starlight-'+skyId} x1="0" y1="0" x2="0" y2="1"><stop stopColor="#fff"/><stop offset=".55" stopColor="#fff" stopOpacity=".75"/><stop offset=".88" stopColor="#fff" stopOpacity="0"/></linearGradient><mask id={'starfade-'+skyId}><rect width="694" height="422" fill={`url(#starlight-${skyId})`}/></mask></defs><g fill="currentColor" mask={`url(#starfade-${skyId})`}>{Array.from({length:150},(_,i)=>[12+(i*137.507%670),8+((i*73.13+i*i*3.11)%360)]).map(([cx,cy],i)=><circle key={i} cx={cx} cy={cy} r={i%17===0?1.15:i%5===0?.75:.48} opacity={.18+(i*7%13)/18}/>)}</g></svg>}

 {known&&['clear','mainly-clear','partly-cloudy'].includes(category)&&(night?<Moon/>:<div className="ambient-orb ambient-sun"/>)}<Meteors enabled={night&&['clear','mainly-clear','partly-cloudy'].includes(category)}/><AmbientEvents enabled={known&&(aircraft||lunarDust)} aircraft={aircraft} night={night} moonVisible={night&&category==='clear'} lunarDust={lunarDust}/>{known&&!clear&&<svg className="ambient-clouds" viewBox="0 0 800 250" preserveAspectRatio="none"><defs><radialGradient id={'cloud-'+skyId}><stop stopColor={night?'#a9bbc6':'#f0f5f5'} stopOpacity=".38"/><stop offset=".55" stopColor={night?'#859aa8':'#d8e4e9'} stopOpacity=".22"/><stop offset="1" stopColor={night?'#6d8798':'#c3d4dd'} stopOpacity="0"/></radialGradient></defs><g fill={`url(#cloud-${skyId})`}><ellipse cx="510" cy="76" rx="175" ry="38"/><ellipse cx="615" cy="92" rx="190" ry="30" opacity=".7"/><ellipse cx="385" cy="93" rx="140" ry="25" opacity=".5"/><ellipse cx="52" cy="165" rx="180" ry="42"/><ellipse cx="165" cy="181" rx="185" ry="28" opacity=".62"/><ellipse cx="775" cy="168" rx="175" ry="35" opacity=".8"/></g></svg>}{rain&&<div className="ambient-rain"/>}{snow&&<div className="ambient-snow"/>}
 <svg className="ambient-city" viewBox="0 0 694 120" preserveAspectRatio="none"><defs><clipPath id={'city-'+skyId}><path d="M0 120V71h25V53h14V44h4v9h14v28h21V66h19V43h7v-8h3v8h8v23h13v24h25V46h15V30h28v-8h3v8h17v50h20V60h25V44h22v-9h3v9h16v33h18V91h26V67h22V55h5V28h3v27h19v23h23V60h26V39h18V26h3v13h18v50h19V69h26V52h12v-9h3v9h20v26h25V62h16V45h23V31h3v14h17v39h24V72h25V58h17v-7h3v7h18v62Z"/></clipPath></defs><path className="city-backdrop" d="M0 120V79h18V64h21V58h19V69h21V47h30V43h3v4h15V73h25V62h25V55h15V61h21V37h14V29h12V37h11V70h31V57h17V52h25V63h24V44h14V38h20V44h11V77h33V54h20V49h26V60h30V35h16V28h3V35h19V73h26V46h17V40h23V46h9V66h29V58h18V52h23V69h32V50h25V46h19V57h21V80h28V120Z"/><path className="city-front" d="M0 120V71h25V53h14V44h4v9h14v28h21V66h19V43h7v-8h3v8h8v23h13v24h25V46h15V30h28v-8h3v8h17v50h20V60h25V44h22v-9h3v9h16v33h18V91h26V67h22V55h5V28h3v27h19v23h23V60h26V39h18V26h3v13h18v50h19V69h26V52h12v-9h3v9h20v26h25V62h16V45h23V31h3v14h17v39h24V72h25V58h17v-7h3v7h18v62Z" fill="currentColor"/>{night&&<g className="city-windows" clipPath={`url(#city-${skyId})`}>{cityWindows.map((window,i)=><rect key={i} {...window}/>)}</g>}</svg>

 </div>;
}
export function Home({wakeEpoch=0,language,timezone,weather:w,temperature,condition,location,stale,player,stationName,station,trackTitle,audioReady,canPlay,pauses,homeCards,visualizerSize,positions,layoutEditing,onSaveLayout,onCancelLayout,shortcuts,t,icon,onWeather,onToggle,onStop,onNavigate,visualizer}:Props){
 const weatherCard=useAmbientCard(layoutEditing,wakeEpoch),forecastCard=useAmbientCard(layoutEditing,wakeEpoch),playbackCard=useAmbientCard(layoutEditing,wakeEpoch);
 const layout=useHomeLayout(positions,layoutEditing),[savingLayout,setSavingLayout]=useState(false),[layoutError,setLayoutError]=useState(false);
 const weatherExpanded=!layoutEditing&&weatherCard.expanded,forecastExpanded=!layoutEditing&&forecastCard.expanded,playbackExpanded=!layoutEditing&&playbackCard.expanded;
 const showWeather=homeCards.includes('weather'),showForecast=homeCards.includes('forecast'),showPlayback=homeCards.includes('playback');
 const grip=(key:HomeKey)=>layoutEditing?<button className="home-drag-handle" data-layout-handle={key} aria-label={`${language==='ro'?'Mută':'Move'} ${key==='visualizer'?(language==='ro'?'vizualizatorul':'visualizer'):t(key==='playback'?'nowPlaying':key)}`} {...layout.handle(key)}>⠿</button>:null;
 const signalHeight={compact:64,balanced:88,large:112}[visualizerSize]||64;
 const transportLayout=!!(showPlayback&&visualizer&&playbackExpanded);
 const rows=transportLayout?`minmax(166px,1fr) ${signalHeight}px 80px`:`minmax(166px,1fr) ${showForecast?'80px':'0px'} ${showPlayback&&visualizer?signalHeight+'px':'0px'} ${showPlayback&&(layoutEditing||!visualizer)?'64px':'0px'}`;
 const expand=language==='ro'?'Extinde':'Expand',collapse=language==='ro'?'Restrânge':'Collapse';
 const hasWeather=typeof temperature==='number'&&Number.isFinite(temperature),active=['playing','paused','buffering','connecting'].includes(player.state);
 const title=player.kind==='radio'?(player.url?stationName:''):player.title,metadata=player.kind==='radio'&&!!player.url&&trackTitle&&trackTitle!==stationName?trackTitle:'';
 const status=player.state==='error'?t('errorState'):t(player.state||'idle'),locale=language==='ro'?'ro-RO':'en-GB';
 const stamp=w.updated_at?new Date(w.updated_at).toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit',timeZone:timezone}):'';
 const labels=language==='ro'?{forecast:'Prognoză 5 zile',wind:'Vânt',humidity:'Umiditate',pressure:'Presiune',uv:'Indice UV'}:{forecast:'5-day forecast',wind:'Wind',humidity:'Humidity',pressure:'Pressure',uv:'UV index'};
 const movable=([...(showWeather?['weather']:[]),...(showForecast?['forecast']:[]),...(showPlayback?['playback']:[]),...(showPlayback&&visualizer?['visualizer']:[])] as HomeKey[]).map(value=>({value,label:value==='forecast'?(language==='ro'?'Prognoză':'Forecast'):value==='visualizer'?(language==='ro'?'Vizualizator':'Visualizer'):t(value==='playback'?'nowPlaying':value)}));
 const days=Array.isArray(w.daily)?w.daily.slice(0,5):[],visibleDays=forecastExpanded?days:days.slice(0,1);
 return <div ref={layout.root} data-visualizer-size={visualizerSize} data-layout-editing={layoutEditing} style={{gridTemplateRows:rows}} className={`home-layout home-v2 ambient-home ${visualizer?'ambient-has-signal':''} ${transportLayout?'transport-expanded':''} ${!playbackExpanded&&visualizer?'playback-in-signal':''}`}>
 {layoutEditing&&createPortal(<div className="home-layout-toolbar"><span>{language==='ro'?'Trage de mânerul cardului':'Drag a card handle'}</span><TouchChoice label={language==='ro'?'Selectează cardul':'Choose card'} value={layout.selected||movable[0]?.value||''} options={movable} closeLabel={language==='ro'?'Închide':'Close'} onChange={async key=>{layout.select(key as HomeKey);return true;}}/><button disabled={savingLayout} onClick={async()=>{setSavingLayout(true);setLayoutError(false);try{if(!await onSaveLayout(layout.draft))setLayoutError(true);}finally{setSavingLayout(false);}}}>{language==='ro'?(savingLayout?'Se salvează…':'Gata'):(savingLayout?'Saving…':'Done')}</button><button disabled={savingLayout} onClick={layout.reset}>{language==='ro'?'Resetează':'Reset'}</button><button disabled={savingLayout} onClick={onCancelLayout}>{t('cancel')}</button>{layoutError&&<span role="alert">{language==='ro'?'Nu s-a salvat. Încearcă din nou.':'Not saved. Try again.'}</span>}</div>,document.querySelector('.app')!)}
 {showWeather&&<section {...layout.props('weather')} className={`home-weather ambient-weather ${weatherExpanded?'':'card-compact'}`} aria-label={t('weather')} onPointerDown={weatherCard.touch} onKeyDown={weatherCard.touch} onClick={e=>{if(!layoutEditing&&!(e.target as HTMLElement).closest('button'))weatherCard.toggle();}}>{grip('weather')}<header className="weather-top"><button className="weather-heading" aria-expanded={weatherExpanded} aria-label={`${weatherExpanded?collapse:expand} ${t('weather')}`} onClick={layoutEditing?undefined:weatherCard.toggle}><span className="weather-location">{location||t('noLocation')}</span><small className={stale?'stale-mark':'weather-updated'}>{stale?t('stale'):stamp?`${t('updated')} ${stamp}`:t('weather')}</small></button><button className="icon-button" aria-label={t('chooseCity')} onClick={onWeather}>{icon('globe',19)}</button></header>
 {hasWeather?<div className="ambient-weather-body"><div className="ambient-current"><div className="temp-row"><span className="temp">{degrees(temperature)}</span><WeatherIcon weather_code={w.current?.weather_code} isDay={w.current?.is_day} size={42}/></div><div className="ambient-condition">{condition||t('weather')}</div><div className="weather-details"><span>{t('feels')} {degrees(w.current?.feels_like_c)}</span></div></div><dl className="ambient-metrics" hidden={!weatherExpanded}><div><dt>{labels.wind}</dt><dd>{measured(w.current?.wind_kmh,'km/h')}</dd></div><div><dt>{labels.humidity}</dt><dd>{measured(w.current?.humidity_pct,'%')}</dd></div><div><dt>{labels.pressure}</dt><dd>{measured(w.current?.pressure_hpa,'hPa')}</dd></div><div><dt>{labels.uv}</dt><dd>{measured(w.current?.uv_index,'')}</dd></div></dl></div>:<button className="weather-empty" onClick={onWeather}><WeatherIcon weather_code={null} size={32}/><span>{location?t('weatherUnavailable'):t('noWeather')}</span><small>{t('chooseCity')} →</small></button>}
 </section>}
 {showForecast&&<section {...layout.props('forecast')} role={layoutEditing?undefined:'button'} tabIndex={layoutEditing?undefined:0} className={`ambient-forecast ${forecastExpanded?'':'card-compact'}`} aria-label={labels.forecast} aria-expanded={forecastExpanded} onClick={layoutEditing?undefined:forecastCard.toggle} onPointerDown={forecastCard.touch} onKeyDown={e=>{forecastCard.touch();if(!layoutEditing&&['Enter',' '].includes(e.key)){e.preventDefault();forecastCard.toggle();}}}>{grip('forecast')}<header><h2>{forecastExpanded?labels.forecast:(language==='ro'?'Astăzi':'Today')}</h2>{w.attribution&&<span className="weather-attribution">Open-Meteo</span>}</header><div className="forecast-line">{days.length?visibleDays.map((day:any)=><div className="forecast-day" key={day.date}><b>{new Date(`${day.date}T12:00:00`).toLocaleDateString(locale,{weekday:'short'})}</b><WeatherIcon weather_code={day.weather_code} isDay={true} size={24}/><span><strong>{degrees(day.max_c)}</strong><i>{degrees(day.min_c)}</i></span></div>):<div className="forecast-unavailable">{t('weatherUnavailable')}</div>}</div></section>}
 {showPlayback&&visualizer&&<div {...layout.props('visualizer')} role={layoutEditing?undefined:'button'} tabIndex={layoutEditing?undefined:0} className="ambient-visualizer" aria-label={`${language==='ro'?'Vizualizator audio':'Audio visualizer'} · ${playbackExpanded?collapse:expand}`} aria-expanded={playbackExpanded} onClick={layoutEditing?undefined:playbackCard.toggle} onPointerDown={playbackCard.touch} onKeyDown={e=>{playbackCard.touch();if(!layoutEditing&&['Enter',' '].includes(e.key)){e.preventDefault();playbackCard.toggle();}}}>{grip('visualizer')}{visualizer}{!playbackExpanded&&<span className="signal-station">{player.kind==='radio'&&<StationArtwork station={station} name={stationName}/>}<span>{title||t('nothingPlaying')}</span></span>}</div>}
 {showPlayback&&<section {...layout.props('playback')} className={`home-focus home-playback ambient-dock ${playbackExpanded?'':'card-compact'} ${player.state||'idle'}`} aria-label={t('nowPlaying')} onPointerDown={playbackCard.touch} onKeyDown={playbackCard.touch}>{grip('playback')}<button className="playback-expand" aria-expanded={playbackExpanded} aria-label={`${playbackExpanded?collapse:expand} ${t('nowPlaying')}`} onClick={playbackCard.toggle}>{player.kind==='radio'&&<StationArtwork station={station} name={stationName}/>}<div className="playback-copy"><div className="playback-caption"><span className="eyebrow">{t(player.kind==='radio'?'radio':active?'localMedia':'nowPlaying')}</span><span className={`player-state ${player.state||'idle'}`}><i aria-hidden="true"/>{status}</span></div><h1 className="playback-source"><MarqueeText text={title||t('nothingPlaying')} active={player.state==='playing'}/></h1>{metadata&&<p className="playback-metadata"><MarqueeText text={metadata} active={player.state==='playing'}/></p>}{!title&&<p className="playback-metadata">{audioReady?(language==='ro'?'Alege un post sau un fișier.':'Choose a station or a file.'):t('chooseOutput')}</p>}</div></button><div className="mini-controls"><button className="primary playback-toggle" aria-label={t(pauses?'pause':'play')} disabled={!pauses&&(!canPlay||!audioReady)} onClick={onToggle}>{icon(pauses?'pause':'play',25)}</button><button className="outline" aria-label={t('stop')} disabled={!player.url&&!active} onClick={onStop}>{icon('stop',20)}</button></div><nav className="ambient-shortcuts" aria-label={t('quickAccess')}>{(['radio','media'] as const).filter(page=>shortcuts.includes(page)).map(page=><button className="shortcut" key={page} onClick={()=>onNavigate(page)}>{icon(page,23)}<b>{t(page)}</b></button>)}</nav></section>}
 </div>;
}
